# SPDX-License-Identifier: Apache-2.0
"""Fused per-token INT8 quant — single-pass bf16->amax->scale->int8.

Camino de producción: PTX nativo embebido (``_PTX_FUSED_QUANT``, editado
bit-exacto E1/E2) ensamblado y lanzado por ``KernelNativo`` (ptxas -> cubin
-> cuLaunchKernel, sin JIT de Triton). El cubin está horneado con
``BLOCK=4096`` y strides unitarios (tensores contiguos, K=4096); cualquier
shape fuera del horneado cae al cuerpo Triton ``_fused_quant_per_token_triton``
(que queda en el archivo SOLO como referencia para tests y fallback del
kill-switch ``GENESIS_PTQ_NATIVO=0``).
"""
from __future__ import annotations

import torch
import triton
import triton.language as tl

try:
    from vllm._genesis.kernels.ptx_runtime import KernelNativo
    from vllm._genesis.kernels.ptx_runtime import habilitado as _ptx_habilitado
except ImportError:  # uso suelto (tests fuera del paquete)
    from ptx_runtime import KernelNativo
    from ptx_runtime import habilitado as _ptx_habilitado

BLOCK_MAX = 8192

# BLOCK horneado en el cubin (constexpr inline del PTX).
_PTX_BLOQUE = 4096

# PTX editado (E1: copysign->lop3 LUT 0xF8; E2: div.full por pot2->mul por
# reciproco) del kernel ``_fused_quant_per_token_triton``. Gate bit-exacto
# (3 semillas) contra el JIT de Triton: /tmp/opencode/tests_ptx/.
_PTX_FUSED_QUANT = r'''//
// Generated by LLVM NVPTX Back-End
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	_fused_quant_per_token_kernel // -- Begin function _fused_quant_per_token_kernel
.extern .shared .align 16 .b8 global_smem[];
                                        // @_fused_quant_per_token_kernel
.visible .entry _fused_quant_per_token_kernel(
	.param .u64 .ptr .global .align 1 _fused_quant_per_token_kernel_param_0,
	.param .u64 .ptr .global .align 1 _fused_quant_per_token_kernel_param_1,
	.param .u64 .ptr .global .align 1 _fused_quant_per_token_kernel_param_2,
	.param .u32 _fused_quant_per_token_kernel_param_3,
	.param .u32 _fused_quant_per_token_kernel_param_4,
	.param .u32 _fused_quant_per_token_kernel_param_5,
	.param .u64 .ptr .global .align 1 _fused_quant_per_token_kernel_param_6,
	.param .u64 .ptr .global .align 1 _fused_quant_per_token_kernel_param_7
)
.reqntid 128
{
	.reg .pred 	%p<41>;
	.reg .b16 	%rs<33>;
	.reg .b32 	%r<369>;
	.reg .b64 	%rd<15>;
	.loc	1 21 0                          // fused_quant_triton.py:21:0
$L__func_begin0:
	.loc	1 21 0                          // fused_quant_triton.py:21:0

// %bb.0:
	ld.param.b64 	%rd8, [_fused_quant_per_token_kernel_param_0];
	ld.param.b64 	%rd9, [_fused_quant_per_token_kernel_param_1];
$L__tmp0:
	.loc	1 33 24                         // fused_quant_triton.py:33:24
	mov.u32 	%r32, %ctaid.x;
	ld.param.b64 	%rd10, [_fused_quant_per_token_kernel_param_2];
	.loc	1 34 24                         // fused_quant_triton.py:34:24
	mov.u32 	%r33, %tid.x;
	and.b32 	%r34, %r33, 127;
	ld.param.b32 	%r35, [_fused_quant_per_token_kernel_param_3];
	and.b32 	%r36, %r33, 31;
	ld.param.b32 	%r37, [_fused_quant_per_token_kernel_param_4];
	shr.u32 	%r38, %r33, 5;
	ld.param.b32 	%r39, [_fused_quant_per_token_kernel_param_5];
	shl.b32 	%r40, %r33, 4;
	and.b32 	%r41, %r40, 2032;
	or.b32 	%r42, %r41, 2048;
	.loc	1 35 18                         // fused_quant_triton.py:35:18
	setp.lt.s32 	%p1, %r41, %r35;
	setp.lt.s32 	%p2, %r42, %r35;
	.loc	1 36 30                         // fused_quant_triton.py:36:30
	mul.lo.s32 	%r43, %r37, %r32;
	.loc	1 36 24                         // fused_quant_triton.py:36:24
	mad.wide.s32 	%rd11, %r43, 2, %rd8;
	.loc	1 36 42                         // fused_quant_triton.py:36:42
	cvt.u64.u32 	%rd12, %r41;
	mad.wide.u32 	%rd1, %r41, 2, %rd11;
	add.s64 	%rd2, %rd1, 16;
	add.s64 	%rd3, %rd1, 4096;
	add.s64 	%rd4, %rd1, 4112;
	mov.b32 	%r5, 0;
	.loc	1 36 16                         // fused_quant_triton.py:36:16
	// begin inline asm
	mov.u32 %r1, %r5;
	mov.u32 %r2, %r5;
	mov.u32 %r3, %r5;
	mov.u32 %r4, %r5;
	@%p1 ld.global.v4.b32 { %r1, %r2, %r3, %r4 }, [ %rd1 + 0 ];
	// end inline asm
	mov.b32 	{%rs1, %rs2}, %r1;
	mov.b32 	{%rs3, %rs4}, %r2;
	mov.b32 	{%rs5, %rs6}, %r3;
	mov.b32 	{%rs7, %rs8}, %r4;
	// begin inline asm
	mov.u32 %r6, %r5;
	mov.u32 %r7, %r5;
	mov.u32 %r8, %r5;
	mov.u32 %r9, %r5;
	@%p1 ld.global.v4.b32 { %r6, %r7, %r8, %r9 }, [ %rd2 + 0 ];
	// end inline asm
	mov.b32 	{%rs9, %rs10}, %r6;
	mov.b32 	{%rs11, %rs12}, %r7;
	mov.b32 	{%rs13, %rs14}, %r8;
	mov.b32 	{%rs15, %rs16}, %r9;
	// begin inline asm
	mov.u32 %r10, %r5;
	mov.u32 %r11, %r5;
	mov.u32 %r12, %r5;
	mov.u32 %r13, %r5;
	@%p2 ld.global.v4.b32 { %r10, %r11, %r12, %r13 }, [ %rd3 + 0 ];
	// end inline asm
	mov.b32 	{%rs17, %rs18}, %r10;
	mov.b32 	{%rs19, %rs20}, %r11;
	mov.b32 	{%rs21, %rs22}, %r12;
	mov.b32 	{%rs23, %rs24}, %r13;
	// begin inline asm
	mov.u32 %r14, %r5;
	mov.u32 %r15, %r5;
	mov.u32 %r16, %r5;
	mov.u32 %r17, %r5;
	@%p2 ld.global.v4.b32 { %r14, %r15, %r16, %r17 }, [ %rd4 + 0 ];
	// end inline asm
	mov.b32 	{%rs25, %rs26}, %r14;
	mov.b32 	{%rs27, %rs28}, %r15;
	mov.b32 	{%rs29, %rs30}, %r16;
	mov.b32 	{%rs31, %rs32}, %r17;
	.loc	1 37 17                         // fused_quant_triton.py:37:17
	cvt.f32.bf16 	%r44, %rs1;
	cvt.f32.bf16 	%r45, %rs2;
	cvt.f32.bf16 	%r46, %rs3;
	cvt.f32.bf16 	%r47, %rs4;
	cvt.f32.bf16 	%r48, %rs5;
	cvt.f32.bf16 	%r49, %rs6;
	cvt.f32.bf16 	%r50, %rs7;
	cvt.f32.bf16 	%r51, %rs8;
	cvt.f32.bf16 	%r52, %rs9;
	cvt.f32.bf16 	%r53, %rs10;
	cvt.f32.bf16 	%r54, %rs11;
	cvt.f32.bf16 	%r55, %rs12;
	cvt.f32.bf16 	%r56, %rs13;
	cvt.f32.bf16 	%r57, %rs14;
	cvt.f32.bf16 	%r58, %rs15;
	cvt.f32.bf16 	%r59, %rs16;
	cvt.f32.bf16 	%r60, %rs17;
	cvt.f32.bf16 	%r61, %rs18;
	cvt.f32.bf16 	%r62, %rs19;
	cvt.f32.bf16 	%r63, %rs20;
	cvt.f32.bf16 	%r64, %rs21;
	cvt.f32.bf16 	%r65, %rs22;
	cvt.f32.bf16 	%r66, %rs23;
	cvt.f32.bf16 	%r67, %rs24;
	cvt.f32.bf16 	%r68, %rs25;
	cvt.f32.bf16 	%r69, %rs26;
	cvt.f32.bf16 	%r70, %rs27;
	cvt.f32.bf16 	%r71, %rs28;
	cvt.f32.bf16 	%r72, %rs29;
	cvt.f32.bf16 	%r73, %rs30;
	cvt.f32.bf16 	%r74, %rs31;
	cvt.f32.bf16 	%r75, %rs32;
	.loc	1 38 25                         // fused_quant_triton.py:38:25
	abs.f32 	%r76, %r44;
	abs.f32 	%r77, %r45;
	abs.f32 	%r78, %r46;
	abs.f32 	%r79, %r47;
	abs.f32 	%r80, %r48;
	abs.f32 	%r81, %r49;
	abs.f32 	%r82, %r50;
	abs.f32 	%r83, %r51;
	abs.f32 	%r84, %r52;
	abs.f32 	%r85, %r53;
	abs.f32 	%r86, %r54;
	abs.f32 	%r87, %r55;
	abs.f32 	%r88, %r56;
	abs.f32 	%r89, %r57;
	abs.f32 	%r90, %r58;
	abs.f32 	%r91, %r59;
	abs.f32 	%r92, %r60;
	abs.f32 	%r93, %r61;
	abs.f32 	%r94, %r62;
	abs.f32 	%r95, %r63;
	abs.f32 	%r96, %r64;
	abs.f32 	%r97, %r65;
	abs.f32 	%r98, %r66;
	abs.f32 	%r99, %r67;
	abs.f32 	%r100, %r68;
	abs.f32 	%r101, %r69;
	abs.f32 	%r102, %r70;
	abs.f32 	%r103, %r71;
	abs.f32 	%r104, %r72;
	abs.f32 	%r105, %r73;
	abs.f32 	%r106, %r74;
	abs.f32 	%r107, %r75;
$L__tmp1:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ fused_quant_triton.py:38:18 ] ]
	max.f32 	%r108, %r76, %r77;
	max.f32 	%r109, %r108, %r78;
	max.f32 	%r110, %r109, %r79;
	max.f32 	%r111, %r110, %r80;
	max.f32 	%r112, %r111, %r81;
	max.f32 	%r113, %r112, %r82;
	max.f32 	%r114, %r113, %r83;
	max.f32 	%r115, %r114, %r84;
	max.f32 	%r116, %r115, %r85;
	max.f32 	%r117, %r116, %r86;
	max.f32 	%r118, %r117, %r87;
	max.f32 	%r119, %r118, %r88;
	max.f32 	%r120, %r119, %r89;
	max.f32 	%r121, %r120, %r90;
	max.f32 	%r122, %r121, %r91;
	max.f32 	%r123, %r122, %r92;
	max.f32 	%r124, %r123, %r93;
	max.f32 	%r125, %r124, %r94;
	max.f32 	%r126, %r125, %r95;
	max.f32 	%r127, %r126, %r96;
	max.f32 	%r128, %r127, %r97;
	max.f32 	%r129, %r128, %r98;
	max.f32 	%r130, %r129, %r99;
	max.f32 	%r131, %r130, %r100;
	max.f32 	%r132, %r131, %r101;
	max.f32 	%r133, %r132, %r102;
	max.f32 	%r134, %r133, %r103;
	max.f32 	%r135, %r134, %r104;
	max.f32 	%r136, %r135, %r105;
	max.f32 	%r137, %r136, %r106;
	max.f32 	%r138, %r137, %r107;
$L__tmp2:
	.loc	2 191 40                        // standard.py:191:40 @[ fused_quant_triton.py:38:18 ]
	shfl.sync.bfly.b32 	%r139, %r138, 16, 31, -1;
$L__tmp3:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ fused_quant_triton.py:38:18 ] ]
	max.f32 	%r140, %r138, %r139;
$L__tmp4:
	.loc	2 191 40                        // standard.py:191:40 @[ fused_quant_triton.py:38:18 ]
	shfl.sync.bfly.b32 	%r141, %r140, 8, 31, -1;
$L__tmp5:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ fused_quant_triton.py:38:18 ] ]
	max.f32 	%r142, %r140, %r141;
$L__tmp6:
	.loc	2 191 40                        // standard.py:191:40 @[ fused_quant_triton.py:38:18 ]
	shfl.sync.bfly.b32 	%r143, %r142, 4, 31, -1;
$L__tmp7:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ fused_quant_triton.py:38:18 ] ]
	max.f32 	%r144, %r142, %r143;
$L__tmp8:
	.loc	2 191 40                        // standard.py:191:40 @[ fused_quant_triton.py:38:18 ]
	shfl.sync.bfly.b32 	%r145, %r144, 2, 31, -1;
$L__tmp9:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ fused_quant_triton.py:38:18 ] ]
	max.f32 	%r146, %r144, %r145;
$L__tmp10:
	.loc	2 191 40                        // standard.py:191:40 @[ fused_quant_triton.py:38:18 ]
	shfl.sync.bfly.b32 	%r147, %r146, 1, 31, -1;
$L__tmp11:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ fused_quant_triton.py:38:18 ] ]
	max.f32 	%r19, %r146, %r147;
$L__tmp12:
	.loc	2 191 40                        // standard.py:191:40 @[ fused_quant_triton.py:38:18 ]
	setp.eq.b32 	%p3, %r36, 0;
	shr.u32 	%r148, %r33, 3;
	and.b32 	%r149, %r148, 12;
	mov.b32 	%r150, global_smem;
	add.s32 	%r18, %r150, %r149;
	// begin inline asm
	@%p3 st.shared.b32 [ %r18 + 0 ], %r19;
	// end inline asm
	bar.sync 	0;
	setp.lt.u32 	%p4, %r34, 4;
	shl.b32 	%r151, %r34, 2;
	add.s32 	%r21, %r150, %r151;
	// begin inline asm
	@%p4 ld.shared.b32 %r20, [ %r21 + 0 ];
	// end inline asm
	shfl.sync.bfly.b32 	%r152, %r20, 2, 31, -1;
$L__tmp13:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ fused_quant_triton.py:38:18 ] ]
	max.f32 	%r153, %r20, %r152;
$L__tmp14:
	.loc	2 191 40                        // standard.py:191:40 @[ fused_quant_triton.py:38:18 ]
	shfl.sync.bfly.b32 	%r154, %r153, 1, 31, -1;
$L__tmp15:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ fused_quant_triton.py:38:18 ] ]
	max.f32 	%r22, %r153, %r154;
$L__tmp16:
	.loc	2 191 40                        // standard.py:191:40 @[ fused_quant_triton.py:38:18 ]
	and.b32 	%r155, %r33, 3;
	setp.eq.b32 	%p7, %r155, 0;
	and.pred 	%p5, %p4, %p7;
	// begin inline asm
	@%p5 st.shared.b32 [ %r21 + 0 ], %r22;
	// end inline asm
	bar.sync 	0;
	ld.shared.b32 	%r156, [global_smem];
	mov.b32 	%r157, 0f42FE0000;
$L__tmp17:
	.loc	1 39 28                         // fused_quant_triton.py:39:28
	div.full.f32 	%r158, %r156, %r157;
	.loc	1 39 36                         // fused_quant_triton.py:39:36
	setp.gt.f32 	%p8, %r158, 0f00000000;
	.loc	1 39 53                         // fused_quant_triton.py:39:53
	selp.f32 	%r23, %r158, 0f3F800000, %p8;
	.loc	1 40 25                         // fused_quant_triton.py:40:25
	mad.wide.u32 	%rd5, %r32, 4, %rd10;
	.loc	1 40 45                         // fused_quant_triton.py:40:45
	or.b32 	%r159, %r36, %r38;
	setp.eq.b32 	%p6, %r159, 0;
	// begin inline asm
	@%p6 st.global.b32 [ %rd5 + 0 ], { %r23 };
	// end inline asm
	.loc	1 41 23                         // fused_quant_triton.py:41:23
	div.full.f32 	%r160, %r44, %r23;
	div.full.f32 	%r161, %r45, %r23;
	div.full.f32 	%r162, %r46, %r23;
	div.full.f32 	%r163, %r47, %r23;
	div.full.f32 	%r164, %r48, %r23;
	div.full.f32 	%r165, %r49, %r23;
	div.full.f32 	%r166, %r50, %r23;
	div.full.f32 	%r167, %r51, %r23;
	div.full.f32 	%r168, %r52, %r23;
	div.full.f32 	%r169, %r53, %r23;
	div.full.f32 	%r170, %r54, %r23;
	div.full.f32 	%r171, %r55, %r23;
	div.full.f32 	%r172, %r56, %r23;
	div.full.f32 	%r173, %r57, %r23;
	div.full.f32 	%r174, %r58, %r23;
	div.full.f32 	%r175, %r59, %r23;
	div.full.f32 	%r176, %r60, %r23;
	div.full.f32 	%r177, %r61, %r23;
	div.full.f32 	%r178, %r62, %r23;
	div.full.f32 	%r179, %r63, %r23;
	div.full.f32 	%r180, %r64, %r23;
	div.full.f32 	%r181, %r65, %r23;
	div.full.f32 	%r182, %r66, %r23;
	div.full.f32 	%r183, %r67, %r23;
	div.full.f32 	%r184, %r68, %r23;
	div.full.f32 	%r185, %r69, %r23;
	div.full.f32 	%r186, %r70, %r23;
	div.full.f32 	%r187, %r71, %r23;
	div.full.f32 	%r188, %r72, %r23;
	div.full.f32 	%r189, %r73, %r23;
	div.full.f32 	%r190, %r74, %r23;
	div.full.f32 	%r191, %r75, %r23;
	.loc	1 46 29                         // fused_quant_triton.py:46:29
	mul.lo.s32 	%r192, %r39, %r32;
	.loc	1 46 23                         // fused_quant_triton.py:46:23
	cvt.s64.s32 	%rd13, %r192;
	add.s64 	%rd14, %rd9, %rd13;
	.loc	1 46 44                         // fused_quant_triton.py:46:44
	add.s64 	%rd6, %rd14, %rd12;
	add.s64 	%rd7, %rd6, 2048;
	.loc	1 42 32                         // fused_quant_triton.py:42:32
	.loc	1 42 40                         // fused_quant_triton.py:42:40
	lop3.b32 	%r193, 0x3f000000, %r161, 0x80000000, 0xF8;
	lop3.b32 	%r194, 0x3f000000, %r160, 0x80000000, 0xF8;
	lop3.b32 	%r195, 0x3f000000, %r163, 0x80000000, 0xF8;
	lop3.b32 	%r196, 0x3f000000, %r162, 0x80000000, 0xF8;
	.loc	1 43 24                         // fused_quant_triton.py:43:24
	add.f32 	%r197, %r162, %r196;
	add.f32 	%r198, %r163, %r195;
	add.f32 	%r199, %r160, %r194;
	add.f32 	%r200, %r161, %r193;
	.loc	1 43 33                         // fused_quant_triton.py:43:33
	cvt.rzi.s32.f32 	%r201, %r200;
	cvt.rzi.s32.f32 	%r202, %r199;
	cvt.rzi.s32.f32 	%r203, %r198;
	cvt.rzi.s32.f32 	%r204, %r197;
	.loc	1 45 41                         // fused_quant_triton.py:45:41
	max.s32 	%r205, %r204, -127;
	max.s32 	%r206, %r203, -127;
	max.s32 	%r207, %r202, -127;
	max.s32 	%r208, %r201, -127;
	min.s32 	%r209, %r208, 127;
	min.s32 	%r210, %r207, 127;
	min.s32 	%r211, %r206, 127;
	min.s32 	%r212, %r205, 127;
	.loc	1 46 74                         // fused_quant_triton.py:46:74
	prmt.b32 	%r213, %r212, %r211, 0x3340U;
	prmt.b32 	%r214, %r210, %r209, 0x3340U;
	prmt.b32 	%r24, %r214, %r213, 0x5410U;
	.loc	1 42 32                         // fused_quant_triton.py:42:32
	.loc	1 42 40                         // fused_quant_triton.py:42:40
	lop3.b32 	%r215, 0x3f000000, %r165, 0x80000000, 0xF8;
	lop3.b32 	%r216, 0x3f000000, %r164, 0x80000000, 0xF8;
	lop3.b32 	%r217, 0x3f000000, %r167, 0x80000000, 0xF8;
	lop3.b32 	%r218, 0x3f000000, %r166, 0x80000000, 0xF8;
	.loc	1 43 24                         // fused_quant_triton.py:43:24
	add.f32 	%r219, %r166, %r218;
	add.f32 	%r220, %r167, %r217;
	add.f32 	%r221, %r164, %r216;
	add.f32 	%r222, %r165, %r215;
	.loc	1 43 33                         // fused_quant_triton.py:43:33
	cvt.rzi.s32.f32 	%r223, %r222;
	cvt.rzi.s32.f32 	%r224, %r221;
	cvt.rzi.s32.f32 	%r225, %r220;
	cvt.rzi.s32.f32 	%r226, %r219;
	.loc	1 45 41                         // fused_quant_triton.py:45:41
	max.s32 	%r227, %r226, -127;
	max.s32 	%r228, %r225, -127;
	max.s32 	%r229, %r224, -127;
	max.s32 	%r230, %r223, -127;
	min.s32 	%r231, %r230, 127;
	min.s32 	%r232, %r229, 127;
	min.s32 	%r233, %r228, 127;
	min.s32 	%r234, %r227, 127;
	.loc	1 46 74                         // fused_quant_triton.py:46:74
	prmt.b32 	%r235, %r234, %r233, 0x3340U;
	prmt.b32 	%r236, %r232, %r231, 0x3340U;
	prmt.b32 	%r25, %r236, %r235, 0x5410U;
	.loc	1 42 32                         // fused_quant_triton.py:42:32
	.loc	1 42 40                         // fused_quant_triton.py:42:40
	lop3.b32 	%r237, 0x3f000000, %r169, 0x80000000, 0xF8;
	lop3.b32 	%r238, 0x3f000000, %r168, 0x80000000, 0xF8;
	lop3.b32 	%r239, 0x3f000000, %r171, 0x80000000, 0xF8;
	lop3.b32 	%r240, 0x3f000000, %r170, 0x80000000, 0xF8;
	.loc	1 43 24                         // fused_quant_triton.py:43:24
	add.f32 	%r241, %r170, %r240;
	add.f32 	%r242, %r171, %r239;
	add.f32 	%r243, %r168, %r238;
	add.f32 	%r244, %r169, %r237;
	.loc	1 43 33                         // fused_quant_triton.py:43:33
	cvt.rzi.s32.f32 	%r245, %r244;
	cvt.rzi.s32.f32 	%r246, %r243;
	cvt.rzi.s32.f32 	%r247, %r242;
	cvt.rzi.s32.f32 	%r248, %r241;
	.loc	1 45 41                         // fused_quant_triton.py:45:41
	max.s32 	%r249, %r248, -127;
	max.s32 	%r250, %r247, -127;
	max.s32 	%r251, %r246, -127;
	max.s32 	%r252, %r245, -127;
	min.s32 	%r253, %r252, 127;
	min.s32 	%r254, %r251, 127;
	min.s32 	%r255, %r250, 127;
	min.s32 	%r256, %r249, 127;
	.loc	1 46 74                         // fused_quant_triton.py:46:74
	prmt.b32 	%r257, %r256, %r255, 0x3340U;
	prmt.b32 	%r258, %r254, %r253, 0x3340U;
	prmt.b32 	%r26, %r258, %r257, 0x5410U;
	.loc	1 42 32                         // fused_quant_triton.py:42:32
	.loc	1 42 40                         // fused_quant_triton.py:42:40
	lop3.b32 	%r259, 0x3f000000, %r173, 0x80000000, 0xF8;
	lop3.b32 	%r260, 0x3f000000, %r172, 0x80000000, 0xF8;
	lop3.b32 	%r261, 0x3f000000, %r175, 0x80000000, 0xF8;
	lop3.b32 	%r262, 0x3f000000, %r174, 0x80000000, 0xF8;
	.loc	1 43 24                         // fused_quant_triton.py:43:24
	add.f32 	%r263, %r174, %r262;
	add.f32 	%r264, %r175, %r261;
	add.f32 	%r265, %r172, %r260;
	add.f32 	%r266, %r173, %r259;
	.loc	1 43 33                         // fused_quant_triton.py:43:33
	cvt.rzi.s32.f32 	%r267, %r266;
	cvt.rzi.s32.f32 	%r268, %r265;
	cvt.rzi.s32.f32 	%r269, %r264;
	cvt.rzi.s32.f32 	%r270, %r263;
	.loc	1 45 41                         // fused_quant_triton.py:45:41
	max.s32 	%r271, %r270, -127;
	max.s32 	%r272, %r269, -127;
	max.s32 	%r273, %r268, -127;
	max.s32 	%r274, %r267, -127;
	min.s32 	%r275, %r274, 127;
	min.s32 	%r276, %r273, 127;
	min.s32 	%r277, %r272, 127;
	min.s32 	%r278, %r271, 127;
	.loc	1 46 74                         // fused_quant_triton.py:46:74
	prmt.b32 	%r279, %r278, %r277, 0x3340U;
	prmt.b32 	%r280, %r276, %r275, 0x3340U;
	prmt.b32 	%r27, %r280, %r279, 0x5410U;
	.loc	1 42 32                         // fused_quant_triton.py:42:32
	.loc	1 42 40                         // fused_quant_triton.py:42:40
	lop3.b32 	%r281, 0x3f000000, %r177, 0x80000000, 0xF8;
	lop3.b32 	%r282, 0x3f000000, %r176, 0x80000000, 0xF8;
	lop3.b32 	%r283, 0x3f000000, %r179, 0x80000000, 0xF8;
	lop3.b32 	%r284, 0x3f000000, %r178, 0x80000000, 0xF8;
	.loc	1 43 24                         // fused_quant_triton.py:43:24
	add.f32 	%r285, %r178, %r284;
	add.f32 	%r286, %r179, %r283;
	add.f32 	%r287, %r176, %r282;
	add.f32 	%r288, %r177, %r281;
	.loc	1 43 33                         // fused_quant_triton.py:43:33
	cvt.rzi.s32.f32 	%r289, %r288;
	cvt.rzi.s32.f32 	%r290, %r287;
	cvt.rzi.s32.f32 	%r291, %r286;
	cvt.rzi.s32.f32 	%r292, %r285;
	.loc	1 45 41                         // fused_quant_triton.py:45:41
	max.s32 	%r293, %r292, -127;
	max.s32 	%r294, %r291, -127;
	max.s32 	%r295, %r290, -127;
	max.s32 	%r296, %r289, -127;
	min.s32 	%r297, %r296, 127;
	min.s32 	%r298, %r295, 127;
	min.s32 	%r299, %r294, 127;
	min.s32 	%r300, %r293, 127;
	.loc	1 46 74                         // fused_quant_triton.py:46:74
	prmt.b32 	%r301, %r300, %r299, 0x3340U;
	prmt.b32 	%r302, %r298, %r297, 0x3340U;
	prmt.b32 	%r28, %r302, %r301, 0x5410U;
	.loc	1 42 32                         // fused_quant_triton.py:42:32
	.loc	1 42 40                         // fused_quant_triton.py:42:40
	lop3.b32 	%r303, 0x3f000000, %r181, 0x80000000, 0xF8;
	lop3.b32 	%r304, 0x3f000000, %r180, 0x80000000, 0xF8;
	lop3.b32 	%r305, 0x3f000000, %r183, 0x80000000, 0xF8;
	lop3.b32 	%r306, 0x3f000000, %r182, 0x80000000, 0xF8;
	.loc	1 43 24                         // fused_quant_triton.py:43:24
	add.f32 	%r307, %r182, %r306;
	add.f32 	%r308, %r183, %r305;
	add.f32 	%r309, %r180, %r304;
	add.f32 	%r310, %r181, %r303;
	.loc	1 43 33                         // fused_quant_triton.py:43:33
	cvt.rzi.s32.f32 	%r311, %r310;
	cvt.rzi.s32.f32 	%r312, %r309;
	cvt.rzi.s32.f32 	%r313, %r308;
	cvt.rzi.s32.f32 	%r314, %r307;
	.loc	1 45 41                         // fused_quant_triton.py:45:41
	max.s32 	%r315, %r314, -127;
	max.s32 	%r316, %r313, -127;
	max.s32 	%r317, %r312, -127;
	max.s32 	%r318, %r311, -127;
	min.s32 	%r319, %r318, 127;
	min.s32 	%r320, %r317, 127;
	min.s32 	%r321, %r316, 127;
	min.s32 	%r322, %r315, 127;
	.loc	1 46 74                         // fused_quant_triton.py:46:74
	prmt.b32 	%r323, %r322, %r321, 0x3340U;
	prmt.b32 	%r324, %r320, %r319, 0x3340U;
	prmt.b32 	%r29, %r324, %r323, 0x5410U;
	.loc	1 42 32                         // fused_quant_triton.py:42:32
	.loc	1 42 40                         // fused_quant_triton.py:42:40
	lop3.b32 	%r325, 0x3f000000, %r185, 0x80000000, 0xF8;
	lop3.b32 	%r326, 0x3f000000, %r184, 0x80000000, 0xF8;
	lop3.b32 	%r327, 0x3f000000, %r187, 0x80000000, 0xF8;
	lop3.b32 	%r328, 0x3f000000, %r186, 0x80000000, 0xF8;
	.loc	1 43 24                         // fused_quant_triton.py:43:24
	add.f32 	%r329, %r186, %r328;
	add.f32 	%r330, %r187, %r327;
	add.f32 	%r331, %r184, %r326;
	add.f32 	%r332, %r185, %r325;
	.loc	1 43 33                         // fused_quant_triton.py:43:33
	cvt.rzi.s32.f32 	%r333, %r332;
	cvt.rzi.s32.f32 	%r334, %r331;
	cvt.rzi.s32.f32 	%r335, %r330;
	cvt.rzi.s32.f32 	%r336, %r329;
	.loc	1 45 41                         // fused_quant_triton.py:45:41
	max.s32 	%r337, %r336, -127;
	max.s32 	%r338, %r335, -127;
	max.s32 	%r339, %r334, -127;
	max.s32 	%r340, %r333, -127;
	min.s32 	%r341, %r340, 127;
	min.s32 	%r342, %r339, 127;
	min.s32 	%r343, %r338, 127;
	min.s32 	%r344, %r337, 127;
	.loc	1 46 74                         // fused_quant_triton.py:46:74
	prmt.b32 	%r345, %r344, %r343, 0x3340U;
	prmt.b32 	%r346, %r342, %r341, 0x3340U;
	prmt.b32 	%r30, %r346, %r345, 0x5410U;
	.loc	1 42 32                         // fused_quant_triton.py:42:32
	.loc	1 42 40                         // fused_quant_triton.py:42:40
	lop3.b32 	%r347, 0x3f000000, %r189, 0x80000000, 0xF8;
	lop3.b32 	%r348, 0x3f000000, %r188, 0x80000000, 0xF8;
	lop3.b32 	%r349, 0x3f000000, %r191, 0x80000000, 0xF8;
	lop3.b32 	%r350, 0x3f000000, %r190, 0x80000000, 0xF8;
	.loc	1 43 24                         // fused_quant_triton.py:43:24
	add.f32 	%r351, %r190, %r350;
	add.f32 	%r352, %r191, %r349;
	add.f32 	%r353, %r188, %r348;
	add.f32 	%r354, %r189, %r347;
	.loc	1 43 33                         // fused_quant_triton.py:43:33
	cvt.rzi.s32.f32 	%r355, %r354;
	cvt.rzi.s32.f32 	%r356, %r353;
	cvt.rzi.s32.f32 	%r357, %r352;
	cvt.rzi.s32.f32 	%r358, %r351;
	.loc	1 45 41                         // fused_quant_triton.py:45:41
	max.s32 	%r359, %r358, -127;
	max.s32 	%r360, %r357, -127;
	max.s32 	%r361, %r356, -127;
	max.s32 	%r362, %r355, -127;
	min.s32 	%r363, %r362, 127;
	min.s32 	%r364, %r361, 127;
	min.s32 	%r365, %r360, 127;
	min.s32 	%r366, %r359, 127;
	.loc	1 46 74                         // fused_quant_triton.py:46:74
	prmt.b32 	%r367, %r366, %r365, 0x3340U;
	prmt.b32 	%r368, %r364, %r363, 0x3340U;
	prmt.b32 	%r31, %r368, %r367, 0x5410U;
	.loc	1 46 65                         // fused_quant_triton.py:46:65
	// begin inline asm
	@%p1 st.global.v4.b32 [ %rd6 + 0 ], { %r24, %r25, %r26, %r27 };
	// end inline asm
	// begin inline asm
	@%p2 st.global.v4.b32 [ %rd7 + 0 ], { %r28, %r29, %r30, %r31 };
	// end inline asm
	.loc	1 46 4                          // fused_quant_triton.py:46:4
	ret;
$L__tmp18:
$L__func_end0:
                                        // -- End function
}
	.file	1 "/home/usuario/Proyectos/genesis-vllm-patches/vllm/_genesis/kernels/fused_quant_triton.py"
	.file	2 "/home/usuario/Proyectos/genesis-vllm-patches/.venv/lib/python3.12/site-packages/triton/language/standard.py"
	.section	.debug_abbrev
	{
.b8 1                                   // Abbreviation Code
.b8 17                                  // DW_TAG_compile_unit
.b8 1                                   // DW_CHILDREN_yes
.b8 37                                  // DW_AT_producer
.b8 8                                   // DW_FORM_string
.b8 19                                  // DW_AT_language
.b8 5                                   // DW_FORM_data2
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 16                                  // DW_AT_stmt_list
.b8 6                                   // DW_FORM_data4
.b8 27                                  // DW_AT_comp_dir
.b8 8                                   // DW_FORM_string
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 2                                   // Abbreviation Code
.b8 46                                  // DW_TAG_subprogram
.b8 0                                   // DW_CHILDREN_no
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 32                                  // DW_AT_inline
.b8 11                                  // DW_FORM_data1
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 3                                   // Abbreviation Code
.b8 46                                  // DW_TAG_subprogram
.b8 1                                   // DW_CHILDREN_yes
.b8 17                                  // DW_AT_low_pc
.b8 1                                   // DW_FORM_addr
.b8 18                                  // DW_AT_high_pc
.b8 1                                   // DW_FORM_addr
.b8 49                                  // DW_AT_abstract_origin
.b8 19                                  // DW_FORM_ref4
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 4                                   // Abbreviation Code
.b8 29                                  // DW_TAG_inlined_subroutine
.b8 1                                   // DW_CHILDREN_yes
.b8 49                                  // DW_AT_abstract_origin
.b8 19                                  // DW_FORM_ref4
.b8 17                                  // DW_AT_low_pc
.b8 1                                   // DW_FORM_addr
.b8 18                                  // DW_AT_high_pc
.b8 1                                   // DW_FORM_addr
.b8 88                                  // DW_AT_call_file
.b8 11                                  // DW_FORM_data1
.b8 89                                  // DW_AT_call_line
.b8 11                                  // DW_FORM_data1
.b8 87                                  // DW_AT_call_column
.b8 11                                  // DW_FORM_data1
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 5                                   // Abbreviation Code
.b8 29                                  // DW_TAG_inlined_subroutine
.b8 0                                   // DW_CHILDREN_no
.b8 49                                  // DW_AT_abstract_origin
.b8 19                                  // DW_FORM_ref4
.b8 17                                  // DW_AT_low_pc
.b8 1                                   // DW_FORM_addr
.b8 18                                  // DW_AT_high_pc
.b8 1                                   // DW_FORM_addr
.b8 88                                  // DW_AT_call_file
.b8 11                                  // DW_FORM_data1
.b8 89                                  // DW_AT_call_line
.b8 11                                  // DW_FORM_data1
.b8 87                                  // DW_AT_call_column
.b8 11                                  // DW_FORM_data1
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 0                                   // EOM(3)
	}
	.section	.debug_info
	{
.b32 214                                // Length of Unit
.b8 2                                   // DWARF version number
.b8 0
.b32 .debug_abbrev                      // Offset Into Abbrev. Section
.b8 8                                   // Address Size (in bytes)
.b8 1                                   // Abbrev [1] 0xb:0xcf DW_TAG_compile_unit
.b8 116                                 // DW_AT_producer
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2                                   // DW_AT_language
.b8 0
.b8 102                                 // DW_AT_name
.b8 117
.b8 115
.b8 101
.b8 100
.b8 95
.b8 113
.b8 117
.b8 97
.b8 110
.b8 116
.b8 95
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line                        // DW_AT_stmt_list
.b8 47                                  // DW_AT_comp_dir
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 117
.b8 115
.b8 117
.b8 97
.b8 114
.b8 105
.b8 111
.b8 47
.b8 80
.b8 114
.b8 111
.b8 121
.b8 101
.b8 99
.b8 116
.b8 111
.b8 115
.b8 47
.b8 103
.b8 101
.b8 110
.b8 101
.b8 115
.b8 105
.b8 115
.b8 45
.b8 118
.b8 108
.b8 108
.b8 109
.b8 45
.b8 112
.b8 97
.b8 116
.b8 99
.b8 104
.b8 101
.b8 115
.b8 47
.b8 118
.b8 108
.b8 108
.b8 109
.b8 47
.b8 95
.b8 103
.b8 101
.b8 110
.b8 101
.b8 115
.b8 105
.b8 115
.b8 47
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 115
.b8 0
.b8 2                                   // Abbrev [2] 0x72:0x20 DW_TAG_subprogram
.b8 95                                  // DW_AT_name
.b8 102
.b8 117
.b8 115
.b8 101
.b8 100
.b8 95
.b8 113
.b8 117
.b8 97
.b8 110
.b8 116
.b8 95
.b8 112
.b8 101
.b8 114
.b8 95
.b8 116
.b8 111
.b8 107
.b8 101
.b8 110
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 0
.b8 1                                   // DW_AT_inline
.b8 3                                   // Abbrev [3] 0x92:0x47 DW_TAG_subprogram
.b64 $L__func_begin0                    // DW_AT_low_pc
.b64 $L__func_end0                      // DW_AT_high_pc
.b32 114                                // DW_AT_abstract_origin
.b8 4                                   // Abbrev [4] 0xa7:0x31 DW_TAG_inlined_subroutine
.b32 114                                // DW_AT_abstract_origin
.b64 $L__tmp1                           // DW_AT_low_pc
.b64 $L__tmp17                          // DW_AT_high_pc
.b8 1                                   // DW_AT_call_file
.b8 38                                  // DW_AT_call_line
.b8 18                                  // DW_AT_call_column
.b8 5                                   // Abbrev [5] 0xbf:0x18 DW_TAG_inlined_subroutine
.b32 114                                // DW_AT_abstract_origin
.b64 $L__tmp1                           // DW_AT_low_pc
.b64 $L__tmp16                          // DW_AT_high_pc
.b8 2                                   // DW_AT_call_file
.b8 191                                 // DW_AT_call_line
.b8 40                                  // DW_AT_call_column
.b8 0                                   // End Of Children Mark
.b8 0                                   // End Of Children Mark
.b8 0                                   // End Of Children Mark
	}
	.section	.debug_macinfo	{	}
'''

# ABI: params runtime en idx (posiciones en la lista completa de args en
# orden de declaracion); horneado = posiciones no consumidas por el cubin,
# verificadas en cada lanzamiento.
_PTQ_KERNEL = KernelNativo(
    "C/fused_quant_triton", _PTX_FUSED_QUANT,
    num_warps=4, shared=16,
    idx=[0, 1, 2, 3, 4, 6], n_runtime=6,
    horneado={5: 1, 7: 1, 8: 1, 9: _PTX_BLOQUE},
)


def is_triton_available() -> bool:
    return True


def is_available() -> bool:
    return torch.cuda.is_available()


@triton.jit
def _fused_quant_per_token_triton(
    x_ptr,
    out_ptr,
    scale_ptr,
    N,
    stride_xm,
    stride_xn,
    stride_out_m,
    stride_out_n,
    stride_scale,
    BLOCK: tl.constexpr,
):
    pid = tl.program_id(0)
    offs = tl.arange(0, BLOCK)
    mask = offs < N
    x = tl.load(x_ptr + pid * stride_xm + offs * stride_xn, mask=mask, other=0.0)
    x_f32 = x.to(tl.float32)
    amax = tl.max(tl.abs(x_f32), axis=0)
    scale = tl.where(amax / 127.0 > 0, amax / 127.0, 1.0)
    tl.store(scale_ptr + pid * stride_scale, scale)
    q_scaled = x_f32 / scale
    bias = tl.where(q_scaled >= 0, 0.5, -0.5)
    q_int = (q_scaled + bias).to(tl.int32)
    q_int = tl.where(q_int > 127, 127, q_int)
    q_int = tl.where(q_int < -127, -127, q_int)
    tl.store(out_ptr + pid * stride_out_m + offs * stride_out_n, q_int.to(tl.int8), mask=mask)


# Compat harness/tests: nombre histórico del cuerpo Triton (solo referencia).
_fused_quant_per_token_kernel = _fused_quant_per_token_triton


def quant_activation_per_token(x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    """Per-token INT8 quant via fused single-pass. [...,K] -> ([...,K] int8, [...,1] fp32)."""
    if not isinstance(x, torch.Tensor):
        raise ValueError("x debe ser torch.Tensor")
    if x.dim() < 1:
        raise ValueError(f"x.dim >=1 requerido, got {x.dim()}")
    if x.numel() == 0:
        return torch.empty_like(x, dtype=torch.int8), torch.ones(x.shape[:-1] + (1,), dtype=torch.float32, device=x.device)
    orig_shape = x.shape
    k = int(orig_shape[-1])
    m = x.numel() // k
    x_2d = x.reshape(m, k)
    n = x_2d.shape[1]
    assert n <= BLOCK_MAX, f"N={n} > BLOCK_MAX={BLOCK_MAX} — fail fast sin fallback"
    block = triton.next_power_of_2(n)
    out_2d = torch.empty((m, n), dtype=torch.int8, device=x.device)
    scale_2d = torch.empty((m,), dtype=torch.float32, device=x.device)
    if _ptx_habilitado() and block == _PTX_BLOQUE and x_2d.stride(1) == 1:
        # Camino nativo: args en EXACTO orden de declaracion (constexpr
        # inline); out/scale recién asignados son contiguos (strides 1,
        # horneados). Grid (m,), 4 warps, 16 B shared — según cubin.
        _PTQ_KERNEL((m,), x_2d, out_2d, scale_2d, n,
                    x_2d.stride(0), x_2d.stride(1),
                    out_2d.stride(0), out_2d.stride(1), scale_2d.stride(0),
                    block)
    else:
        _fused_quant_per_token_triton[(m,)](
            x_2d, out_2d, scale_2d, n,
            x_2d.stride(0), x_2d.stride(1), out_2d.stride(0), out_2d.stride(1), scale_2d.stride(0),
            BLOCK=block,
        )
    return out_2d.reshape(orig_shape), scale_2d.reshape(orig_shape[:-1] + (1,)).contiguous()


fused_quant_per_token = quant_activation_per_token
fused_quant_triton = quant_activation_per_token

__all__ = ["quant_activation_per_token", "fused_quant_per_token", "fused_quant_triton", "is_available", "is_triton_available"]
