"""PN40 — DFlash drafter omnibus optimization (Genesis-original).

Strict-superset optimization for DFlash spec-decode that:
  - DOES NOT compete with FA2 attention (PN37 lesson learned)
  - Reduces kernel launch overhead (per-layer loop fusion)
  - Improves memory/cache utilization (persistent buffer pool)
  - Adapts to workload (short/long ctx, code, free-form)
  - Provides runtime stability sentinel + auto-fallback
  - Composes additively with PN21/PN23/PN24 (other DFlash patches)

Architecture (4 sub-kernels under one umbrella):

  A. Fused per-layer K-norm Triton kernel
     Replaces `for i in range(L): ops.rms_norm(...)` loop in
     `qwen3_dflash.py:397-404` (per-layer K-norm). Single kernel launch
     vs L launches (L=5 on 27B drafter, L=8 on 35B drafter).
     Saves: L-1 kernel launches per draft step ≈ 12-35 µs.

  B. Persistent K/V buffer pool (Python orchestrator)
     Reuses `all_k_normed` / `all_v_buffer` allocations across draft
     steps instead of fresh `torch.empty_like()` each step.
     Saves: ~50-150 µs Ampere malloc overhead per step.

  C. Adaptive DFlash N controller (mirror SGLang [1, 3, 5] tier policy)
     EMA-based acceptance length tracking; auto-shifts N down on reject
     clusters, up on hit clusters. Per-workload tuning.
     Variable: +5-30% TPS depending on workload mix.

  D. Workload classifier + auto-fallback
     Cheap (no GPU sync) classifier picks which sub-kernels engage per
     request: short-ctx, long-ctx, code-query, free-form. Stability
     sentinel disables PN40 on NaN/Inf or AL drop > 0.5.

This v1 file implements ONLY Sub-kernel A (fused K-norm). Sub-kernels
B/C/D land in follow-up commits to keep diff reviewable. The orchestrator
shape exists from the start so the API is stable.

Eligibility (no-regression contract):
  - DFlash drafter present (config.architectures contains "DFlashDraftModel")
  - K tensor BF16, head_dim ∈ {64, 128} (covers 27B + 35B drafters)
  - L (num drafter layers) ∈ [2, 16] (handles edge cases)
  - num_ctx ≥ 1 (any non-empty draft step)
  - SM 8.6+ (Ampere; on SM 8.9+ kernel still works, just less critical)
  - GENESIS_ENABLE_PN40_DFLASH_OMNIBUS=1 (default OFF until A/B validates)

Author: Sandermage (Sander) Barzov Aleksandr, Ukraine, Odessa.
"""
from __future__ import annotations

import logging
import os

import torch

log = logging.getLogger("genesis.kernels.pn40")

try:
    from vllm._genesis.kernels.ptx_runtime import KernelNativo
    from vllm._genesis.kernels.ptx_runtime import habilitado as _ptx_habilitado
except ImportError:  # uso suelto (tests fuera del paquete)
    from ptx_runtime import KernelNativo
    from ptx_runtime import habilitado as _ptx_habilitado

_ENV_ENABLE = "GENESIS_ENABLE_PN40_DFLASH_OMNIBUS"
_ENV_SUB_A = "GENESIS_PN40_ENABLE_SUB_A"  # fused K-norm (default ON if PN40 ON)


def env_enabled() -> bool:
    return os.environ.get(_ENV_ENABLE, "").strip().lower() in (
        "1", "true", "yes", "on"
    )


def sub_a_enabled() -> bool:
    """Sub-kernel A toggle (default: ON when PN40 master is ON)."""
    if not env_enabled():
        return False
    val = os.environ.get(_ENV_SUB_A, "").strip().lower()
    if val in ("0", "false", "no", "off"):
        return False
    return True  # default ON


# ───────────────────────────────────────────────────────────────────
# Sub-kernel A: fused per-layer K-norm
# ───────────────────────────────────────────────────────────────────

_CACHED_K_NORM_KERNEL = None

# PTX editado (E2: div.full por pot2 -> mul por recíproco) del kernel
# ``_pn40_fused_k_norm_triton``, horneado con ``N_per_kv=8`` (H=8 kv heads,
# drafter 35B) y ``BLOCK_D=128`` (D=128), strides unitarios en la dim D
# (tensores contiguos). Gate bit-exacto (3 semillas) contra el JIT de
# Triton: /tmp/opencode/tests_ptx/. ``eps`` es param runtime (f32).
_PTX_K_NORM = r'''//
// Generated by LLVM NVPTX Back-End
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	_pn40_fused_k_norm_kernel // -- Begin function _pn40_fused_k_norm_kernel
.extern .shared .align 16 .b8 global_smem[];
.global .align 1 .b8 _$_str[11] = {95, 95, 67, 85, 68, 65, 95, 70, 84, 90};
.global .align 1 .b8 _$_str_$_2[17] = {95, 95, 67, 85, 68, 65, 95, 80, 82, 69, 67, 95, 83, 81, 82, 84};
                                        // @_pn40_fused_k_norm_kernel
.visible .entry _pn40_fused_k_norm_kernel(
	.param .u64 .ptr .global .align 1 _pn40_fused_k_norm_kernel_param_0,
	.param .u64 .ptr .global .align 1 _pn40_fused_k_norm_kernel_param_1,
	.param .u64 .ptr .global .align 1 _pn40_fused_k_norm_kernel_param_2,
	.param .u32 _pn40_fused_k_norm_kernel_param_3,
	.param .u32 _pn40_fused_k_norm_kernel_param_4,
	.param .u32 _pn40_fused_k_norm_kernel_param_5,
	.param .u32 _pn40_fused_k_norm_kernel_param_6,
	.param .f32 _pn40_fused_k_norm_kernel_param_7,
	.param .u64 .ptr .global .align 1 _pn40_fused_k_norm_kernel_param_8,
	.param .u64 .ptr .global .align 1 _pn40_fused_k_norm_kernel_param_9
)
.reqntid 128
{
	.reg .pred 	%p<6>;
	.reg .b16 	%rs<19>;
	.reg .b32 	%r<217>;
	.reg .b64 	%rd<23>;
	.loc	1 92 0                          // pn40_dflash_omnibus.py:92:0
$L__func_begin0:
	.loc	1 92 0                          // pn40_dflash_omnibus.py:92:0

// %bb.0:                               // %__nv_sqrtf.exit
	ld.param.b64 	%rd18, [_pn40_fused_k_norm_kernel_param_0];
	ld.param.b64 	%rd19, [_pn40_fused_k_norm_kernel_param_1];
$L__tmp0:
	.loc	1 110 29                        // pn40_dflash_omnibus.py:110:29
	mov.u32 	%r27, %ctaid.x;
	ld.param.b64 	%rd20, [_pn40_fused_k_norm_kernel_param_2];
	.loc	1 111 28                        // pn40_dflash_omnibus.py:111:28
	mov.u32 	%r28, %ctaid.y;
	ld.param.b32 	%r29, [_pn40_fused_k_norm_kernel_param_3];
	.loc	1 113 26                        // pn40_dflash_omnibus.py:113:26
	mov.u32 	%r30, %tid.x;
	and.b32 	%r31, %r30, 127;
	ld.param.b32 	%r32, [_pn40_fused_k_norm_kernel_param_4];
	and.b32 	%r33, %r30, 31;
	ld.param.b32 	%r34, [_pn40_fused_k_norm_kernel_param_5];
	ld.param.b32 	%r35, [_pn40_fused_k_norm_kernel_param_6];
	ld.param.b32 	%r36, [_pn40_fused_k_norm_kernel_param_7];
	.loc	1 117 34                        // pn40_dflash_omnibus.py:117:34
	mad.lo.s32 	%r37, %r35, %r27, %r31;
	.loc	1 118 29                        // pn40_dflash_omnibus.py:118:29
	mad.wide.s32 	%rd1, %r37, 2, %rd19;
	mov.b16 	%rs2, 0;
	mov.pred 	%p1, -1;
	.loc	1 118 21                        // pn40_dflash_omnibus.py:118:21
	// begin inline asm
	mov.u16 %rs1, %rs2;
	@%p1 ld.global.b16 { %rs1 }, [ %rd1 + 0 ];
	// end inline asm
	.loc	1 118 67                        // pn40_dflash_omnibus.py:118:67
	cvt.f32.bf16 	%r38, %rs1;
	.loc	1 123 23                        // pn40_dflash_omnibus.py:123:23
	mul.lo.s32 	%r39, %r29, %r27;
	.loc	1 124 14                        // pn40_dflash_omnibus.py:124:14
	mad.lo.s32 	%r40, %r32, %r28, %r39;
	.loc	1 126 14                        // pn40_dflash_omnibus.py:126:14
	add.s32 	%r41, %r40, %r31;
	.loc	1 128 31                        // pn40_dflash_omnibus.py:128:31
	mul.wide.s32 	%rd21, %r41, 2;
	add.s64 	%rd2, %rd18, %rd21;
	.loc	1 128 20                        // pn40_dflash_omnibus.py:128:20
	// begin inline asm
	mov.u16 %rs3, %rs2;
	@%p1 ld.global.b16 { %rs3 }, [ %rd2 + 0 ];
	// end inline asm
	.loc	1 128 69                        // pn40_dflash_omnibus.py:128:69
	cvt.f32.bf16 	%r42, %rs3;
	.loc	1 131 25                        // pn40_dflash_omnibus.py:131:25
	mul.f32 	%r43, %r42, %r42;
$L__tmp1:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r44, %r43, 16, 31, -1;
$L__tmp2:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	fma.rn.f32 	%r45, %r42, %r42, %r44;
$L__tmp3:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r46, %r45, 8, 31, -1;
$L__tmp4:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r47, %r45, %r46;
$L__tmp5:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r48, %r47, 4, 31, -1;
$L__tmp6:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r49, %r47, %r48;
$L__tmp7:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r50, %r49, 2, 31, -1;
$L__tmp8:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r51, %r49, %r50;
$L__tmp9:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r52, %r51, 1, 31, -1;
$L__tmp10:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r2, %r51, %r52;
$L__tmp11:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	setp.eq.b32 	%p2, %r33, 0;
	shr.u32 	%r53, %r30, 3;
	and.b32 	%r54, %r53, 12;
	mov.b32 	%r55, global_smem;
	add.s32 	%r1, %r55, %r54;
	// begin inline asm
	@%p2 st.shared.b32 [ %r1 + 0 ], %r2;
	// end inline asm
	bar.sync 	0;
	setp.lt.u32 	%p3, %r31, 4;
	shl.b32 	%r56, %r31, 2;
	add.s32 	%r4, %r55, %r56;
	// begin inline asm
	@%p3 ld.shared.b32 %r3, [ %r4 + 0 ];
	// end inline asm
	shfl.sync.bfly.b32 	%r57, %r3, 2, 31, -1;
$L__tmp12:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r58, %r3, %r57;
$L__tmp13:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r59, %r58, 1, 31, -1;
$L__tmp14:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r5, %r58, %r59;
$L__tmp15:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	and.b32 	%r60, %r30, 3;
	setp.eq.b32 	%p5, %r60, 0;
	and.pred 	%p4, %p3, %p5;
	// begin inline asm
	@%p4 st.shared.b32 [ %r4 + 0 ], %r5;
	// end inline asm
	bar.sync 	0;
	ld.shared.b32 	%r61, [global_smem];
	mov.b32 	%r62, 0f43000000;
$L__tmp16:
	.loc	1 131 38                        // pn40_dflash_omnibus.py:131:38
	mul.f32 	%r63, %r61, 0f3c000000;
	.loc	1 132 38                        // pn40_dflash_omnibus.py:132:38
	add.f32 	%r64, %r36, %r63;
	.loc	1 132 32                        // pn40_dflash_omnibus.py:132:32
	sqrt.approx.ftz.f32 	%r65, %r64;
	mov.b32 	%r66, 0f3F800000;
	.loc	1 132 24                        // pn40_dflash_omnibus.py:132:24
	div.full.f32 	%r67, %r66, %r65;
	.loc	1 133 23                        // pn40_dflash_omnibus.py:133:23
	mul.f32 	%r68, %r67, %r42;
	.loc	1 133 33                        // pn40_dflash_omnibus.py:133:33
	mul.f32 	%r69, %r68, %r38;
	.loc	1 137 24                        // pn40_dflash_omnibus.py:137:24
	add.s64 	%rd3, %rd20, %rd21;
	.loc	1 138 24                        // pn40_dflash_omnibus.py:138:24
	cvt.rn.bf16.f32 	%rs4, %r69;
	.loc	1 138 12                        // pn40_dflash_omnibus.py:138:12
	// begin inline asm
	@%p1 st.global.b16 [ %rd3 + 0 ], { %rs4 };
	// end inline asm
	.loc	1 128 31                        // pn40_dflash_omnibus.py:128:31
	mul.wide.s32 	%rd22, %r34, 2;
	add.s64 	%rd4, %rd2, %rd22;
	.loc	1 128 20                        // pn40_dflash_omnibus.py:128:20
	// begin inline asm
	mov.u16 %rs5, %rs2;
	@%p1 ld.global.b16 { %rs5 }, [ %rd4 + 0 ];
	// end inline asm
	.loc	1 128 69                        // pn40_dflash_omnibus.py:128:69
	cvt.f32.bf16 	%r70, %rs5;
	.loc	1 131 25                        // pn40_dflash_omnibus.py:131:25
	mul.f32 	%r71, %r70, %r70;
$L__tmp17:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	bar.sync 	0;
	shfl.sync.bfly.b32 	%r72, %r71, 16, 31, -1;
$L__tmp18:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	fma.rn.f32 	%r73, %r70, %r70, %r72;
$L__tmp19:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r74, %r73, 8, 31, -1;
$L__tmp20:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r75, %r73, %r74;
$L__tmp21:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r76, %r75, 4, 31, -1;
$L__tmp22:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r77, %r75, %r76;
$L__tmp23:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r78, %r77, 2, 31, -1;
$L__tmp24:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r79, %r77, %r78;
$L__tmp25:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r80, %r79, 1, 31, -1;
$L__tmp26:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r6, %r79, %r80;
$L__tmp27:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	// begin inline asm
	@%p2 st.shared.b32 [ %r1 + 0 ], %r6;
	// end inline asm
	bar.sync 	0;
	// begin inline asm
	@%p3 ld.shared.b32 %r7, [ %r4 + 0 ];
	// end inline asm
	shfl.sync.bfly.b32 	%r81, %r7, 2, 31, -1;
$L__tmp28:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r82, %r7, %r81;
$L__tmp29:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r83, %r82, 1, 31, -1;
$L__tmp30:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r8, %r82, %r83;
$L__tmp31:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	// begin inline asm
	@%p4 st.shared.b32 [ %r4 + 0 ], %r8;
	// end inline asm
	bar.sync 	0;
	ld.shared.b32 	%r84, [global_smem];
$L__tmp32:
	.loc	1 131 38                        // pn40_dflash_omnibus.py:131:38
	mul.f32 	%r85, %r84, 0f3c000000;
	.loc	1 132 38                        // pn40_dflash_omnibus.py:132:38
	add.f32 	%r86, %r36, %r85;
	.loc	1 132 32                        // pn40_dflash_omnibus.py:132:32
	sqrt.approx.ftz.f32 	%r87, %r86;
	.loc	1 132 24                        // pn40_dflash_omnibus.py:132:24
	div.full.f32 	%r88, %r66, %r87;
	.loc	1 133 23                        // pn40_dflash_omnibus.py:133:23
	mul.f32 	%r89, %r88, %r70;
	.loc	1 133 33                        // pn40_dflash_omnibus.py:133:33
	mul.f32 	%r90, %r89, %r38;
	.loc	1 137 24                        // pn40_dflash_omnibus.py:137:24
	add.s64 	%rd5, %rd3, %rd22;
	.loc	1 138 24                        // pn40_dflash_omnibus.py:138:24
	cvt.rn.bf16.f32 	%rs6, %r90;
	.loc	1 138 12                        // pn40_dflash_omnibus.py:138:12
	// begin inline asm
	@%p1 st.global.b16 [ %rd5 + 0 ], { %rs6 };
	// end inline asm
	.loc	1 128 31                        // pn40_dflash_omnibus.py:128:31
	add.s64 	%rd6, %rd4, %rd22;
	.loc	1 128 20                        // pn40_dflash_omnibus.py:128:20
	// begin inline asm
	mov.u16 %rs7, %rs2;
	@%p1 ld.global.b16 { %rs7 }, [ %rd6 + 0 ];
	// end inline asm
	.loc	1 128 69                        // pn40_dflash_omnibus.py:128:69
	cvt.f32.bf16 	%r91, %rs7;
	.loc	1 131 25                        // pn40_dflash_omnibus.py:131:25
	mul.f32 	%r92, %r91, %r91;
$L__tmp33:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	bar.sync 	0;
	shfl.sync.bfly.b32 	%r93, %r92, 16, 31, -1;
$L__tmp34:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	fma.rn.f32 	%r94, %r91, %r91, %r93;
$L__tmp35:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r95, %r94, 8, 31, -1;
$L__tmp36:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r96, %r94, %r95;
$L__tmp37:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r97, %r96, 4, 31, -1;
$L__tmp38:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r98, %r96, %r97;
$L__tmp39:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r99, %r98, 2, 31, -1;
$L__tmp40:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r100, %r98, %r99;
$L__tmp41:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r101, %r100, 1, 31, -1;
$L__tmp42:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r9, %r100, %r101;
$L__tmp43:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	// begin inline asm
	@%p2 st.shared.b32 [ %r1 + 0 ], %r9;
	// end inline asm
	bar.sync 	0;
	// begin inline asm
	@%p3 ld.shared.b32 %r10, [ %r4 + 0 ];
	// end inline asm
	shfl.sync.bfly.b32 	%r102, %r10, 2, 31, -1;
$L__tmp44:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r103, %r10, %r102;
$L__tmp45:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r104, %r103, 1, 31, -1;
$L__tmp46:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r11, %r103, %r104;
$L__tmp47:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	// begin inline asm
	@%p4 st.shared.b32 [ %r4 + 0 ], %r11;
	// end inline asm
	bar.sync 	0;
	ld.shared.b32 	%r105, [global_smem];
$L__tmp48:
	.loc	1 131 38                        // pn40_dflash_omnibus.py:131:38
	mul.f32 	%r106, %r105, 0f3c000000;
	.loc	1 132 38                        // pn40_dflash_omnibus.py:132:38
	add.f32 	%r107, %r36, %r106;
	.loc	1 132 32                        // pn40_dflash_omnibus.py:132:32
	sqrt.approx.ftz.f32 	%r108, %r107;
	.loc	1 132 24                        // pn40_dflash_omnibus.py:132:24
	div.full.f32 	%r109, %r66, %r108;
	.loc	1 133 23                        // pn40_dflash_omnibus.py:133:23
	mul.f32 	%r110, %r109, %r91;
	.loc	1 133 33                        // pn40_dflash_omnibus.py:133:33
	mul.f32 	%r111, %r110, %r38;
	.loc	1 137 24                        // pn40_dflash_omnibus.py:137:24
	add.s64 	%rd7, %rd5, %rd22;
	.loc	1 138 24                        // pn40_dflash_omnibus.py:138:24
	cvt.rn.bf16.f32 	%rs8, %r111;
	.loc	1 138 12                        // pn40_dflash_omnibus.py:138:12
	// begin inline asm
	@%p1 st.global.b16 [ %rd7 + 0 ], { %rs8 };
	// end inline asm
	.loc	1 128 31                        // pn40_dflash_omnibus.py:128:31
	add.s64 	%rd8, %rd6, %rd22;
	.loc	1 128 20                        // pn40_dflash_omnibus.py:128:20
	// begin inline asm
	mov.u16 %rs9, %rs2;
	@%p1 ld.global.b16 { %rs9 }, [ %rd8 + 0 ];
	// end inline asm
	.loc	1 128 69                        // pn40_dflash_omnibus.py:128:69
	cvt.f32.bf16 	%r112, %rs9;
	.loc	1 131 25                        // pn40_dflash_omnibus.py:131:25
	mul.f32 	%r113, %r112, %r112;
$L__tmp49:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	bar.sync 	0;
	shfl.sync.bfly.b32 	%r114, %r113, 16, 31, -1;
$L__tmp50:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	fma.rn.f32 	%r115, %r112, %r112, %r114;
$L__tmp51:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r116, %r115, 8, 31, -1;
$L__tmp52:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r117, %r115, %r116;
$L__tmp53:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r118, %r117, 4, 31, -1;
$L__tmp54:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r119, %r117, %r118;
$L__tmp55:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r120, %r119, 2, 31, -1;
$L__tmp56:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r121, %r119, %r120;
$L__tmp57:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r122, %r121, 1, 31, -1;
$L__tmp58:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r12, %r121, %r122;
$L__tmp59:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	// begin inline asm
	@%p2 st.shared.b32 [ %r1 + 0 ], %r12;
	// end inline asm
	bar.sync 	0;
	// begin inline asm
	@%p3 ld.shared.b32 %r13, [ %r4 + 0 ];
	// end inline asm
	shfl.sync.bfly.b32 	%r123, %r13, 2, 31, -1;
$L__tmp60:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r124, %r13, %r123;
$L__tmp61:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r125, %r124, 1, 31, -1;
$L__tmp62:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r14, %r124, %r125;
$L__tmp63:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	// begin inline asm
	@%p4 st.shared.b32 [ %r4 + 0 ], %r14;
	// end inline asm
	bar.sync 	0;
	ld.shared.b32 	%r126, [global_smem];
$L__tmp64:
	.loc	1 131 38                        // pn40_dflash_omnibus.py:131:38
	mul.f32 	%r127, %r126, 0f3c000000;
	.loc	1 132 38                        // pn40_dflash_omnibus.py:132:38
	add.f32 	%r128, %r36, %r127;
	.loc	1 132 32                        // pn40_dflash_omnibus.py:132:32
	sqrt.approx.ftz.f32 	%r129, %r128;
	.loc	1 132 24                        // pn40_dflash_omnibus.py:132:24
	div.full.f32 	%r130, %r66, %r129;
	.loc	1 133 23                        // pn40_dflash_omnibus.py:133:23
	mul.f32 	%r131, %r130, %r112;
	.loc	1 133 33                        // pn40_dflash_omnibus.py:133:33
	mul.f32 	%r132, %r131, %r38;
	.loc	1 137 24                        // pn40_dflash_omnibus.py:137:24
	add.s64 	%rd9, %rd7, %rd22;
	.loc	1 138 24                        // pn40_dflash_omnibus.py:138:24
	cvt.rn.bf16.f32 	%rs10, %r132;
	.loc	1 138 12                        // pn40_dflash_omnibus.py:138:12
	// begin inline asm
	@%p1 st.global.b16 [ %rd9 + 0 ], { %rs10 };
	// end inline asm
	.loc	1 128 31                        // pn40_dflash_omnibus.py:128:31
	add.s64 	%rd10, %rd8, %rd22;
	.loc	1 128 20                        // pn40_dflash_omnibus.py:128:20
	// begin inline asm
	mov.u16 %rs11, %rs2;
	@%p1 ld.global.b16 { %rs11 }, [ %rd10 + 0 ];
	// end inline asm
	.loc	1 128 69                        // pn40_dflash_omnibus.py:128:69
	cvt.f32.bf16 	%r133, %rs11;
	.loc	1 131 25                        // pn40_dflash_omnibus.py:131:25
	mul.f32 	%r134, %r133, %r133;
$L__tmp65:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	bar.sync 	0;
	shfl.sync.bfly.b32 	%r135, %r134, 16, 31, -1;
$L__tmp66:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	fma.rn.f32 	%r136, %r133, %r133, %r135;
$L__tmp67:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r137, %r136, 8, 31, -1;
$L__tmp68:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r138, %r136, %r137;
$L__tmp69:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r139, %r138, 4, 31, -1;
$L__tmp70:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r140, %r138, %r139;
$L__tmp71:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r141, %r140, 2, 31, -1;
$L__tmp72:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r142, %r140, %r141;
$L__tmp73:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r143, %r142, 1, 31, -1;
$L__tmp74:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r15, %r142, %r143;
$L__tmp75:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	// begin inline asm
	@%p2 st.shared.b32 [ %r1 + 0 ], %r15;
	// end inline asm
	bar.sync 	0;
	// begin inline asm
	@%p3 ld.shared.b32 %r16, [ %r4 + 0 ];
	// end inline asm
	shfl.sync.bfly.b32 	%r144, %r16, 2, 31, -1;
$L__tmp76:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r145, %r16, %r144;
$L__tmp77:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r146, %r145, 1, 31, -1;
$L__tmp78:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r17, %r145, %r146;
$L__tmp79:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	// begin inline asm
	@%p4 st.shared.b32 [ %r4 + 0 ], %r17;
	// end inline asm
	bar.sync 	0;
	ld.shared.b32 	%r147, [global_smem];
$L__tmp80:
	.loc	1 131 38                        // pn40_dflash_omnibus.py:131:38
	mul.f32 	%r148, %r147, 0f3c000000;
	.loc	1 132 38                        // pn40_dflash_omnibus.py:132:38
	add.f32 	%r149, %r36, %r148;
	.loc	1 132 32                        // pn40_dflash_omnibus.py:132:32
	sqrt.approx.ftz.f32 	%r150, %r149;
	.loc	1 132 24                        // pn40_dflash_omnibus.py:132:24
	div.full.f32 	%r151, %r66, %r150;
	.loc	1 133 23                        // pn40_dflash_omnibus.py:133:23
	mul.f32 	%r152, %r151, %r133;
	.loc	1 133 33                        // pn40_dflash_omnibus.py:133:33
	mul.f32 	%r153, %r152, %r38;
	.loc	1 137 24                        // pn40_dflash_omnibus.py:137:24
	add.s64 	%rd11, %rd9, %rd22;
	.loc	1 138 24                        // pn40_dflash_omnibus.py:138:24
	cvt.rn.bf16.f32 	%rs12, %r153;
	.loc	1 138 12                        // pn40_dflash_omnibus.py:138:12
	// begin inline asm
	@%p1 st.global.b16 [ %rd11 + 0 ], { %rs12 };
	// end inline asm
	.loc	1 128 31                        // pn40_dflash_omnibus.py:128:31
	add.s64 	%rd12, %rd10, %rd22;
	.loc	1 128 20                        // pn40_dflash_omnibus.py:128:20
	// begin inline asm
	mov.u16 %rs13, %rs2;
	@%p1 ld.global.b16 { %rs13 }, [ %rd12 + 0 ];
	// end inline asm
	.loc	1 128 69                        // pn40_dflash_omnibus.py:128:69
	cvt.f32.bf16 	%r154, %rs13;
	.loc	1 131 25                        // pn40_dflash_omnibus.py:131:25
	mul.f32 	%r155, %r154, %r154;
$L__tmp81:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	bar.sync 	0;
	shfl.sync.bfly.b32 	%r156, %r155, 16, 31, -1;
$L__tmp82:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	fma.rn.f32 	%r157, %r154, %r154, %r156;
$L__tmp83:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r158, %r157, 8, 31, -1;
$L__tmp84:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r159, %r157, %r158;
$L__tmp85:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r160, %r159, 4, 31, -1;
$L__tmp86:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r161, %r159, %r160;
$L__tmp87:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r162, %r161, 2, 31, -1;
$L__tmp88:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r163, %r161, %r162;
$L__tmp89:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r164, %r163, 1, 31, -1;
$L__tmp90:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r18, %r163, %r164;
$L__tmp91:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	// begin inline asm
	@%p2 st.shared.b32 [ %r1 + 0 ], %r18;
	// end inline asm
	bar.sync 	0;
	// begin inline asm
	@%p3 ld.shared.b32 %r19, [ %r4 + 0 ];
	// end inline asm
	shfl.sync.bfly.b32 	%r165, %r19, 2, 31, -1;
$L__tmp92:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r166, %r19, %r165;
$L__tmp93:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r167, %r166, 1, 31, -1;
$L__tmp94:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r20, %r166, %r167;
$L__tmp95:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	// begin inline asm
	@%p4 st.shared.b32 [ %r4 + 0 ], %r20;
	// end inline asm
	bar.sync 	0;
	ld.shared.b32 	%r168, [global_smem];
$L__tmp96:
	.loc	1 131 38                        // pn40_dflash_omnibus.py:131:38
	mul.f32 	%r169, %r168, 0f3c000000;
	.loc	1 132 38                        // pn40_dflash_omnibus.py:132:38
	add.f32 	%r170, %r36, %r169;
	.loc	1 132 32                        // pn40_dflash_omnibus.py:132:32
	sqrt.approx.ftz.f32 	%r171, %r170;
	.loc	1 132 24                        // pn40_dflash_omnibus.py:132:24
	div.full.f32 	%r172, %r66, %r171;
	.loc	1 133 23                        // pn40_dflash_omnibus.py:133:23
	mul.f32 	%r173, %r172, %r154;
	.loc	1 133 33                        // pn40_dflash_omnibus.py:133:33
	mul.f32 	%r174, %r173, %r38;
	.loc	1 137 24                        // pn40_dflash_omnibus.py:137:24
	add.s64 	%rd13, %rd11, %rd22;
	.loc	1 138 24                        // pn40_dflash_omnibus.py:138:24
	cvt.rn.bf16.f32 	%rs14, %r174;
	.loc	1 138 12                        // pn40_dflash_omnibus.py:138:12
	// begin inline asm
	@%p1 st.global.b16 [ %rd13 + 0 ], { %rs14 };
	// end inline asm
	.loc	1 128 31                        // pn40_dflash_omnibus.py:128:31
	add.s64 	%rd14, %rd12, %rd22;
	.loc	1 128 20                        // pn40_dflash_omnibus.py:128:20
	// begin inline asm
	mov.u16 %rs15, %rs2;
	@%p1 ld.global.b16 { %rs15 }, [ %rd14 + 0 ];
	// end inline asm
	.loc	1 128 69                        // pn40_dflash_omnibus.py:128:69
	cvt.f32.bf16 	%r175, %rs15;
	.loc	1 131 25                        // pn40_dflash_omnibus.py:131:25
	mul.f32 	%r176, %r175, %r175;
$L__tmp97:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	bar.sync 	0;
	shfl.sync.bfly.b32 	%r177, %r176, 16, 31, -1;
$L__tmp98:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	fma.rn.f32 	%r178, %r175, %r175, %r177;
$L__tmp99:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r179, %r178, 8, 31, -1;
$L__tmp100:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r180, %r178, %r179;
$L__tmp101:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r181, %r180, 4, 31, -1;
$L__tmp102:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r182, %r180, %r181;
$L__tmp103:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r183, %r182, 2, 31, -1;
$L__tmp104:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r184, %r182, %r183;
$L__tmp105:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r185, %r184, 1, 31, -1;
$L__tmp106:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r21, %r184, %r185;
$L__tmp107:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	// begin inline asm
	@%p2 st.shared.b32 [ %r1 + 0 ], %r21;
	// end inline asm
	bar.sync 	0;
	// begin inline asm
	@%p3 ld.shared.b32 %r22, [ %r4 + 0 ];
	// end inline asm
	shfl.sync.bfly.b32 	%r186, %r22, 2, 31, -1;
$L__tmp108:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r187, %r22, %r186;
$L__tmp109:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r188, %r187, 1, 31, -1;
$L__tmp110:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r23, %r187, %r188;
$L__tmp111:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	// begin inline asm
	@%p4 st.shared.b32 [ %r4 + 0 ], %r23;
	// end inline asm
	bar.sync 	0;
	ld.shared.b32 	%r189, [global_smem];
$L__tmp112:
	.loc	1 131 38                        // pn40_dflash_omnibus.py:131:38
	mul.f32 	%r190, %r189, 0f3c000000;
	.loc	1 132 38                        // pn40_dflash_omnibus.py:132:38
	add.f32 	%r191, %r36, %r190;
	.loc	1 132 32                        // pn40_dflash_omnibus.py:132:32
	sqrt.approx.ftz.f32 	%r192, %r191;
	.loc	1 132 24                        // pn40_dflash_omnibus.py:132:24
	div.full.f32 	%r193, %r66, %r192;
	.loc	1 133 23                        // pn40_dflash_omnibus.py:133:23
	mul.f32 	%r194, %r193, %r175;
	.loc	1 133 33                        // pn40_dflash_omnibus.py:133:33
	mul.f32 	%r195, %r194, %r38;
	.loc	1 137 24                        // pn40_dflash_omnibus.py:137:24
	add.s64 	%rd15, %rd13, %rd22;
	.loc	1 138 24                        // pn40_dflash_omnibus.py:138:24
	cvt.rn.bf16.f32 	%rs16, %r195;
	.loc	1 138 12                        // pn40_dflash_omnibus.py:138:12
	// begin inline asm
	@%p1 st.global.b16 [ %rd15 + 0 ], { %rs16 };
	// end inline asm
	.loc	1 128 31                        // pn40_dflash_omnibus.py:128:31
	add.s64 	%rd16, %rd14, %rd22;
	.loc	1 128 20                        // pn40_dflash_omnibus.py:128:20
	// begin inline asm
	mov.u16 %rs17, %rs2;
	@%p1 ld.global.b16 { %rs17 }, [ %rd16 + 0 ];
	// end inline asm
	.loc	1 128 69                        // pn40_dflash_omnibus.py:128:69
	cvt.f32.bf16 	%r196, %rs17;
	.loc	1 131 25                        // pn40_dflash_omnibus.py:131:25
	mul.f32 	%r197, %r196, %r196;
$L__tmp113:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	bar.sync 	0;
	shfl.sync.bfly.b32 	%r198, %r197, 16, 31, -1;
$L__tmp114:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	fma.rn.f32 	%r199, %r196, %r196, %r198;
$L__tmp115:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r200, %r199, 8, 31, -1;
$L__tmp116:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r201, %r199, %r200;
$L__tmp117:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r202, %r201, 4, 31, -1;
$L__tmp118:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r203, %r201, %r202;
$L__tmp119:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r204, %r203, 2, 31, -1;
$L__tmp120:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r205, %r203, %r204;
$L__tmp121:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r206, %r205, 1, 31, -1;
$L__tmp122:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r24, %r205, %r206;
$L__tmp123:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	// begin inline asm
	@%p2 st.shared.b32 [ %r1 + 0 ], %r24;
	// end inline asm
	bar.sync 	0;
	// begin inline asm
	@%p3 ld.shared.b32 %r25, [ %r4 + 0 ];
	// end inline asm
	shfl.sync.bfly.b32 	%r207, %r25, 2, 31, -1;
$L__tmp124:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r208, %r25, %r207;
$L__tmp125:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	shfl.sync.bfly.b32 	%r209, %r208, 1, 31, -1;
$L__tmp126:
	.loc	2 263 15                        // standard.py:263:15 @[ standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ] ]
	add.f32 	%r26, %r208, %r209;
$L__tmp127:
	.loc	2 293 36                        // standard.py:293:36 @[ pn40_dflash_omnibus.py:131:21 ]
	// begin inline asm
	@%p4 st.shared.b32 [ %r4 + 0 ], %r26;
	// end inline asm
	bar.sync 	0;
	ld.shared.b32 	%r210, [global_smem];
$L__tmp128:
	.loc	1 131 38                        // pn40_dflash_omnibus.py:131:38
	mul.f32 	%r211, %r210, 0f3c000000;
	.loc	1 132 38                        // pn40_dflash_omnibus.py:132:38
	add.f32 	%r212, %r36, %r211;
	.loc	1 132 32                        // pn40_dflash_omnibus.py:132:32
	sqrt.approx.ftz.f32 	%r213, %r212;
	.loc	1 132 24                        // pn40_dflash_omnibus.py:132:24
	div.full.f32 	%r214, %r66, %r213;
	.loc	1 133 23                        // pn40_dflash_omnibus.py:133:23
	mul.f32 	%r215, %r214, %r196;
	.loc	1 133 33                        // pn40_dflash_omnibus.py:133:33
	mul.f32 	%r216, %r215, %r38;
	.loc	1 137 24                        // pn40_dflash_omnibus.py:137:24
	add.s64 	%rd17, %rd15, %rd22;
	.loc	1 138 24                        // pn40_dflash_omnibus.py:138:24
	cvt.rn.bf16.f32 	%rs18, %r216;
	.loc	1 138 12                        // pn40_dflash_omnibus.py:138:12
	// begin inline asm
	@%p1 st.global.b16 [ %rd17 + 0 ], { %rs18 };
	// end inline asm
	.loc	1 121 4                         // pn40_dflash_omnibus.py:121:4
	ret;
$L__tmp129:
$L__func_end0:
                                        // -- End function
}
	.file	1 "/home/usuario/Proyectos/genesis-vllm-patches/vllm/_genesis/kernels/pn40_dflash_omnibus.py"
	.file	2 "/home/usuario/Proyectos/genesis-vllm-patches/.venv/lib/python3.12/site-packages/triton/language/standard.py"
	.section	.debug_abbrev
	{
.b8 1                                   // Abbreviation Code
.b8 17                                  // DW_TAG_compile_unit
.b8 1                                   // DW_CHILDREN_yes
.b8 37                                  // DW_AT_producer
.b8 8                                   // DW_FORM_string
.b8 19                                  // DW_AT_language
.b8 5                                   // DW_FORM_data2
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 16                                  // DW_AT_stmt_list
.b8 6                                   // DW_FORM_data4
.b8 27                                  // DW_AT_comp_dir
.b8 8                                   // DW_FORM_string
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 2                                   // Abbreviation Code
.b8 46                                  // DW_TAG_subprogram
.b8 0                                   // DW_CHILDREN_no
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 32                                  // DW_AT_inline
.b8 11                                  // DW_FORM_data1
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 3                                   // Abbreviation Code
.b8 46                                  // DW_TAG_subprogram
.b8 1                                   // DW_CHILDREN_yes
.b8 17                                  // DW_AT_low_pc
.b8 1                                   // DW_FORM_addr
.b8 18                                  // DW_AT_high_pc
.b8 1                                   // DW_FORM_addr
.b8 49                                  // DW_AT_abstract_origin
.b8 19                                  // DW_FORM_ref4
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 4                                   // Abbreviation Code
.b8 29                                  // DW_TAG_inlined_subroutine
.b8 1                                   // DW_CHILDREN_yes
.b8 49                                  // DW_AT_abstract_origin
.b8 19                                  // DW_FORM_ref4
.b8 17                                  // DW_AT_low_pc
.b8 1                                   // DW_FORM_addr
.b8 18                                  // DW_AT_high_pc
.b8 1                                   // DW_FORM_addr
.b8 88                                  // DW_AT_call_file
.b8 11                                  // DW_FORM_data1
.b8 89                                  // DW_AT_call_line
.b8 11                                  // DW_FORM_data1
.b8 87                                  // DW_AT_call_column
.b8 11                                  // DW_FORM_data1
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 5                                   // Abbreviation Code
.b8 29                                  // DW_TAG_inlined_subroutine
.b8 0                                   // DW_CHILDREN_no
.b8 49                                  // DW_AT_abstract_origin
.b8 19                                  // DW_FORM_ref4
.b8 17                                  // DW_AT_low_pc
.b8 1                                   // DW_FORM_addr
.b8 18                                  // DW_AT_high_pc
.b8 1                                   // DW_FORM_addr
.b8 88                                  // DW_AT_call_file
.b8 11                                  // DW_FORM_data1
.b8 89                                  // DW_AT_call_line
.b8 5                                   // DW_FORM_data2
.b8 87                                  // DW_AT_call_column
.b8 11                                  // DW_FORM_data1
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 0                                   // EOM(3)
	}
	.section	.debug_info
	{
.b32 212                                // Length of Unit
.b8 2                                   // DWARF version number
.b8 0
.b32 .debug_abbrev                      // Offset Into Abbrev. Section
.b8 8                                   // Address Size (in bytes)
.b8 1                                   // Abbrev [1] 0xb:0xcd DW_TAG_compile_unit
.b8 116                                 // DW_AT_producer
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2                                   // DW_AT_language
.b8 0
.b8 112                                 // DW_AT_name
.b8 110
.b8 52
.b8 48
.b8 95
.b8 100
.b8 102
.b8 108
.b8 97
.b8 115
.b8 104
.b8 95
.b8 111
.b8 109
.b8 110
.b8 105
.b8 98
.b8 117
.b8 115
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line                        // DW_AT_stmt_list
.b8 47                                  // DW_AT_comp_dir
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 117
.b8 115
.b8 117
.b8 97
.b8 114
.b8 105
.b8 111
.b8 47
.b8 80
.b8 114
.b8 111
.b8 121
.b8 101
.b8 99
.b8 116
.b8 111
.b8 115
.b8 47
.b8 103
.b8 101
.b8 110
.b8 101
.b8 115
.b8 105
.b8 115
.b8 45
.b8 118
.b8 108
.b8 108
.b8 109
.b8 45
.b8 112
.b8 97
.b8 116
.b8 99
.b8 104
.b8 101
.b8 115
.b8 47
.b8 118
.b8 108
.b8 108
.b8 109
.b8 47
.b8 95
.b8 103
.b8 101
.b8 110
.b8 101
.b8 115
.b8 105
.b8 115
.b8 47
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 115
.b8 0
.b8 2                                   // Abbrev [2] 0x73:0x1c DW_TAG_subprogram
.b8 95                                  // DW_AT_name
.b8 112
.b8 110
.b8 52
.b8 48
.b8 95
.b8 102
.b8 117
.b8 115
.b8 101
.b8 100
.b8 95
.b8 107
.b8 95
.b8 110
.b8 111
.b8 114
.b8 109
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 0
.b8 1                                   // DW_AT_inline
.b8 3                                   // Abbrev [3] 0x8f:0x48 DW_TAG_subprogram
.b64 $L__func_begin0                    // DW_AT_low_pc
.b64 $L__func_end0                      // DW_AT_high_pc
.b32 115                                // DW_AT_abstract_origin
.b8 4                                   // Abbrev [4] 0xa4:0x32 DW_TAG_inlined_subroutine
.b32 115                                // DW_AT_abstract_origin
.b64 $L__tmp1                           // DW_AT_low_pc
.b64 $L__tmp128                         // DW_AT_high_pc
.b8 1                                   // DW_AT_call_file
.b8 131                                 // DW_AT_call_line
.b8 21                                  // DW_AT_call_column
.b8 5                                   // Abbrev [5] 0xbc:0x19 DW_TAG_inlined_subroutine
.b32 115                                // DW_AT_abstract_origin
.b64 $L__tmp2                           // DW_AT_low_pc
.b64 $L__tmp127                         // DW_AT_high_pc
.b8 2                                   // DW_AT_call_file
.b8 37                                  // DW_AT_call_line
.b8 1
.b8 36                                  // DW_AT_call_column
.b8 0                                   // End Of Children Mark
.b8 0                                   // End Of Children Mark
.b8 0                                   // End Of Children Mark
	}
	.section	.debug_macinfo	{	}
'''

_PTX_K_NORM_KERNEL = None  # singleton lazy (ensambla una vez por proceso)


def _get_ptx_k_norm_kernel() -> KernelNativo:
    """KernelNativo del K-norm, creado una sola vez (thread-safe vía
    ``KernelNativo._cargar`` para el cubin; la instancia es idempotente)."""
    global _PTX_K_NORM_KERNEL
    if _PTX_K_NORM_KERNEL is None:
        _PTX_K_NORM_KERNEL = KernelNativo(
            "D/pn40_k_norm", _PTX_K_NORM,
            num_warps=4, shared=16,
            idx=[0, 1, 2, 3, 4, 5, 7, 10], n_runtime=8,
            horneado={6: 1, 8: 1, 9: 8, 11: 128},
        )
    return _PTX_K_NORM_KERNEL


def _build_fused_k_norm_kernel():
    """Lazy-build Triton kernel. Cached so repeated calls are free."""
    global _CACHED_K_NORM_KERNEL
    if _CACHED_K_NORM_KERNEL is not None:
        return _CACHED_K_NORM_KERNEL

    import triton
    import triton.language as tl

    @triton.jit
    def _pn40_fused_k_norm_triton(
        K_in_ptr,            # [L, N, H, D]
        W_ptr,               # [L, D] — per-layer norm weights
        K_out_ptr,           # [L, N, H, D]
        sK_l, sK_n, sK_h, sK_d,
        sW_l, sW_d,
        N_per_kv: tl.constexpr,
        eps,
        BLOCK_D: tl.constexpr,
    ):
        """One CTA owns one (layer, ctx_pos). Iterates H heads inner.

        For each head:
          x = K_in[layer, ctx_pos, head, :]         # [D]
          var = mean(x * x)
          x_normed = x * rsqrt(var + eps)
          K_out[layer, ctx_pos, head, :] = x_normed * W[layer, :]
        """
        layer_id = tl.program_id(0)
        ctx_pos = tl.program_id(1)

        offs_d = tl.arange(0, BLOCK_D)
        d_mask = offs_d < BLOCK_D  # always true for power-of-2 BLOCK_D == HEAD_DIM

        # Load per-layer norm weight [D]
        w_offsets = layer_id * sW_l + offs_d * sW_d
        w_tile = tl.load(W_ptr + w_offsets, mask=d_mask, other=0.0).to(tl.float32)

        # Iterate heads (cheap, small constant for GQA configs)
        for h_off in tl.static_range(N_per_kv):
            x_offsets = (
                layer_id * sK_l
                + ctx_pos * sK_n
                + h_off * sK_h
                + offs_d * sK_d
            )
            x = tl.load(K_in_ptr + x_offsets, mask=d_mask, other=0.0).to(tl.float32)

            # RMSNorm: x * rsqrt(mean(x^2) + eps)
            var = tl.sum(x * x, axis=0) / BLOCK_D
            inv_rms = 1.0 / tl.sqrt(var + eps)
            x_normed = x * inv_rms * w_tile

            o_offsets = x_offsets  # same layout for output
            tl.store(
                K_out_ptr + o_offsets,
                x_normed.to(K_out_ptr.dtype.element_ty),
                mask=d_mask,
            )

    _CACHED_K_NORM_KERNEL = _pn40_fused_k_norm_triton
    return _CACHED_K_NORM_KERNEL


def fused_k_norm(k_in, weights, eps: float, out=None):
    """Fused per-layer K-norm.

    Args:
        k_in:    [L, N, H, D] BF16
        weights: [L, D] BF16/FP32
        eps:     float
        out:     [L, N, H, D] BF16 buffer (optional; allocated if None)

    Returns:
        out (allocated or passed) with norm applied.
    """
    assert k_in.is_cuda, "PN40 requires CUDA tensor"
    assert k_in.dim() == 4, f"k_in must be [L,N,H,D]; got {k_in.shape}"
    assert weights.dim() == 2, f"weights must be [L,D]; got {weights.shape}"
    L, N, H, D = k_in.shape
    Lw, Dw = weights.shape
    assert Lw == L, f"weights L ({Lw}) != k_in L ({L})"
    assert Dw == D, f"weights D ({Dw}) != k_in D ({D})"

    if out is None:
        out = k_in.new_empty((L, N, H, D))
    assert out.shape == k_in.shape

    if (
        _ptx_habilitado()
        and H == 8
        and D == 128
        and k_in.dtype is torch.bfloat16
        and weights.dtype is torch.bfloat16
        and out.dtype is torch.bfloat16
        and k_in.stride(3) == 1
        and weights.stride(1) == 1
    ):
        # Camino nativo: args en EXACTO orden de declaracion (constexpr
        # inline). Cubin horneado con sK_d=1, sW_d=1, N_per_kv=8, BLOCK_D=128
        # (guardados arriba). Grid (L, N), 4 warps, 16 B shared.
        _get_ptx_k_norm_kernel()((L, N), k_in, weights, out,
                                 k_in.stride(0), k_in.stride(1),
                                 k_in.stride(2), k_in.stride(3),
                                 weights.stride(0), weights.stride(1),
                                 H, float(eps), D)
        return out

    kernel = _build_fused_k_norm_kernel()
    grid = (L, N)
    BLOCK_D = D
    kernel[grid](
        k_in, weights, out,
        k_in.stride(0), k_in.stride(1), k_in.stride(2), k_in.stride(3),
        weights.stride(0), weights.stride(1),
        N_per_kv=H,
        eps=eps,
        BLOCK_D=BLOCK_D,
    )
    return out


# ───────────────────────────────────────────────────────────────────
# Eligibility predicates (no-regression contract)
# ───────────────────────────────────────────────────────────────────


def is_sub_a_eligible(k_shape, k_dtype) -> bool:
    """Sub-kernel A eligibility: cheap, no GPU sync.

    k_shape: tuple/torch.Size [L, N, H, D]
    k_dtype: torch.dtype
    """
    import torch

    if not sub_a_enabled():
        return False
    if len(k_shape) != 4:
        return False
    L, N, H, D = k_shape
    if not (2 <= L <= 16):
        return False
    if N < 1:
        return False
    if D not in (64, 128):
        return False
    if k_dtype not in (torch.bfloat16, torch.float16):
        return False
    return True


# ═══════════════════════════════════════════════════════════════════
# Sub-kernel C: Universal adaptive spec-decode K/N controller
# Applies to: MTP K (PROD 27B/35B) + DFlash N (test 27B/35B)
# ═══════════════════════════════════════════════════════════════════

_ENV_SUB_C = "GENESIS_PN40_ENABLE_SUB_C"


def sub_c_enabled() -> bool:
    """Sub-kernel C toggle (default ON when PN40 master ON)."""
    if not env_enabled():
        return False
    val = os.environ.get(_ENV_SUB_C, "").strip().lower()
    if val in ("0", "false", "no", "off"):
        return False
    return True


class AdaptiveSpecKController:
    """Universal adaptive K/N controller for spec-decode (MTP, DFlash, ngram).

    Mirrors SGLang's tier-policy from
    `python/sglang/srt/managers/scheduler.py` `AdaptiveSpecParams` —
    EMA-tracked acceptance length + hysteresis bands shift K up/down
    between configured tiers based on observed acceptance rate.

    State (per spec_method):
      - tiers: list of K values (e.g. [0, 1, 3, 5] — K=0 means skip spec)
      - current_idx: current tier index
      - ema_al: EMA of acceptance length (0.0..K_max)
      - ema_alpha: EMA decay rate (default 0.2)
      - up_threshold: shift up if ema_al > tier[current_idx] * up_threshold
      - down_threshold: shift down if ema_al < tier[current_idx] * down_threshold

    Stability:
      - bounded state machine (no unbounded loops)
      - reset on engine restart (instance per StructuredOutputManager)
      - disable on NaN/Inf in observed AL

    Usage:
      controller = AdaptiveSpecKController(tiers=[0, 1, 3, 5], base_k=5)
      ...per accepted batch:
        controller.observe(accepted_len)
      ...before next propose:
        k = controller.current_k()
    """

    def __init__(
        self,
        tiers: list[int],
        base_k: int,
        ema_alpha: float = 0.2,
        up_threshold: float = 0.85,
        down_threshold: float = 0.55,
    ):
        assert len(tiers) >= 1, "at least one tier required"
        assert base_k in tiers, f"base_k {base_k} must be in tiers {tiers}"
        self.tiers = sorted(tiers)
        self.current_idx = self.tiers.index(base_k)
        self.base_k = base_k
        self.ema_alpha = ema_alpha
        self.up_threshold = up_threshold
        self.down_threshold = down_threshold
        self.ema_al: float = float(base_k)
        self.observation_count: int = 0
        self.disabled: bool = False
        self.disable_reason: str | None = None
        # [v7.72 workload-aware tier override] Per-workload class K bias.
        # When request._genesis_pn40_workload_class is set, current_k()
        # returns biased K instead of pure controller decision.
        # See classify_workload() for class taxonomy.
        self._workload_class: str | None = None
        self._workload_bias_table: dict[str, int] = {
            # Code workloads have predictable token streams → high acceptance →
            # benefit from MAX tier (or +1 from controller's idx)
            "code": +1,
            # Long context: KV thrashing with high K + worse acceptance →
            # bias DOWN by 1 tier from controller's choice
            "long_ctx": -1,
            # Short / free-form: trust controller (no bias)
            "short_ctx": 0,
            "free_form": 0,
        }

    def set_workload_class(self, workload_class: str | None) -> None:
        """Update per-request workload class. Read by current_k() to bias K.

        Cheap (no allocation, no GPU sync). Pass None to clear bias.
        """
        if workload_class is not None and workload_class not in self._workload_bias_table:
            # Unknown class → treat as no bias (defensive)
            workload_class = None
        self._workload_class = workload_class

    def current_k(self) -> int:
        """Cheap getter — returns current tier K, biased by workload class.

        No GPU sync. If disabled → returns base_k. If no workload class set
        OR class is unknown → returns pure controller tier.
        """
        if self.disabled:
            return self.base_k  # fall back to user-configured
        idx = self.current_idx
        bias = self._workload_bias_table.get(self._workload_class or "", 0)
        idx = max(0, min(len(self.tiers) - 1, idx + bias))
        return self.tiers[idx]

    def observe(self, accepted_len: float) -> None:
        """Observe an accepted-length sample, update EMA, possibly shift tier."""
        if self.disabled:
            return
        # NaN/Inf sentinel
        if accepted_len != accepted_len or accepted_len < 0 or accepted_len > 100:
            self.disabled = True
            self.disable_reason = (
                f"invalid AL observation {accepted_len!r}, controller disabled"
            )
            return

        self.ema_al = (1 - self.ema_alpha) * self.ema_al + self.ema_alpha * accepted_len
        self.observation_count += 1

        # Warmup grace period — don't shift in first 10 observations
        if self.observation_count < 10:
            return

        cur_k = self.tiers[self.current_idx]
        if cur_k == 0:
            # Already at K=0 — only path UP is observing high acceptance on the
            # NEXT non-zero tier. Cheap re-engage policy: shift up after 30 obs
            # if EMA still > 0 (proxy: there were some hits).
            if self.observation_count - 10 > 30 and self.ema_al > 0.5:
                self.current_idx = min(self.current_idx + 1, len(self.tiers) - 1)
                self.observation_count = 0
            return

        # Hysteresis: shift up if AL approaches current K, down if far below
        up_thr = cur_k * self.up_threshold
        down_thr = cur_k * self.down_threshold

        if self.ema_al >= up_thr and self.current_idx < len(self.tiers) - 1:
            self.current_idx += 1
            self.observation_count = 0
        elif self.ema_al <= down_thr and self.current_idx > 0:
            self.current_idx -= 1
            self.observation_count = 0

    def state_dict(self) -> dict:
        """For diagnostics + serialization."""
        return {
            "tiers": list(self.tiers),
            "current_k": self.current_k(),
            "ema_al": self.ema_al,
            "observation_count": self.observation_count,
            "disabled": self.disabled,
            "disable_reason": self.disable_reason,
        }


# Default tier policies (env-overridable, per spec_method)
_DEFAULT_TIERS = {
    "mtp_3": [0, 1, 3],          # MTP K=3 base (27B PROD, 35B PROD)
    "dflash_5": [0, 1, 3, 5],    # DFlash N=5 base (27B+DFlash)
    "dflash_3": [0, 1, 3],       # DFlash N=3 base (35B+DFlash)
    "ngram": [0, 1, 3, 5, 7],    # ngram base (legacy P77 territory)
}


def get_default_tiers(spec_method: str, base_k: int) -> list[int]:
    """Resolve default tier policy by spec method + base K."""
    key = f"{spec_method}_{base_k}"
    return _DEFAULT_TIERS.get(key, [0, max(1, base_k // 2), base_k])


# ═══════════════════════════════════════════════════════════════════
# Sub-kernel D: Universal stability sentinel + workload classifier
# Applies to ALL 4 configs (MTP + DFlash, 27B + 35B)
# ═══════════════════════════════════════════════════════════════════

_ENV_SUB_D = "GENESIS_PN40_ENABLE_SUB_D"


def sub_d_enabled() -> bool:
    """Sub-kernel D toggle (default ON when PN40 master ON)."""
    if not env_enabled():
        return False
    val = os.environ.get(_ENV_SUB_D, "").strip().lower()
    if val in ("0", "false", "no", "off"):
        return False
    return True


def classify_workload(prompt_text: str | None, prompt_len: int) -> str:
    """Cheap (no GPU sync) workload classifier.

    Returns one of: "code", "long_ctx", "short_ctx", "free_form"

    - "code": detected via tool-call markers, code fences, or fim tokens
              in last 256 chars of prompt
    - "long_ctx": prompt_len >= 16K tokens
    - "short_ctx": prompt_len < 1K tokens
    - "free_form": everything else (default tier)

    Used by orchestrator to select tier policy + buffer pool size.
    """
    if prompt_len >= 16_384:
        return "long_ctx"
    if prompt_text is not None:
        # Check last ~256 chars only (cheap)
        tail = prompt_text[-256:] if len(prompt_text) > 256 else prompt_text
        for sig in ("```", "<tool_call>", "<|fim_", "def ", "function"):
            if sig in tail:
                return "code"
    if prompt_len < 1_024:
        return "short_ctx"
    return "free_form"


class StabilitySentinel:
    """Universal stability monitor for spec-decode optimizations.

    Tracks AL over a sliding window. If AL drops by >threshold (default 0.5)
    over `window_size` observations relative to the long-running EMA, OR if
    NaN/Inf is observed, the sentinel raises a flag that orchestrator reads
    to disable PN40 sub-kernels for the affected request.

    Per-spec-method (separate state for MTP vs DFlash). Reset on engine
    restart.
    """

    def __init__(
        self,
        window_size: int = 50,
        drop_threshold: float = 0.5,
        ema_alpha: float = 0.05,  # slow EMA = stable baseline
    ):
        self.window_size = window_size
        self.drop_threshold = drop_threshold
        self.ema_alpha = ema_alpha
        self.long_ema_al: float = 0.0
        self.recent_window: list[float] = []
        self.tripped: bool = False
        self.trip_reason: str | None = None
        self.trip_count: int = 0

    def observe(self, accepted_len: float) -> bool:
        """Observe AL sample. Returns True if sentinel just tripped this step."""
        # NaN/Inf → trip immediately
        if accepted_len != accepted_len or accepted_len < 0 or accepted_len > 100:
            if not self.tripped:
                self.tripped = True
                self.trip_reason = f"invalid AL: {accepted_len!r}"
                self.trip_count += 1
                return True
            return False

        # Slow EMA for stable baseline
        if self.long_ema_al == 0.0:
            self.long_ema_al = accepted_len
        self.long_ema_al = (
            (1 - self.ema_alpha) * self.long_ema_al + self.ema_alpha * accepted_len
        )

        # Sliding window
        self.recent_window.append(accepted_len)
        if len(self.recent_window) > self.window_size:
            self.recent_window.pop(0)

        # Window vs baseline drop check (only after warmup)
        if len(self.recent_window) >= self.window_size:
            window_avg = sum(self.recent_window) / len(self.recent_window)
            if (
                self.long_ema_al > 0
                and (self.long_ema_al - window_avg) > self.drop_threshold
            ):
                if not self.tripped:
                    self.tripped = True
                    self.trip_reason = (
                        f"AL drop: baseline {self.long_ema_al:.2f} → "
                        f"window {window_avg:.2f} (Δ {self.long_ema_al - window_avg:.2f} "
                        f"> threshold {self.drop_threshold})"
                    )
                    self.trip_count += 1
                    return True
        return False

    def reset(self) -> None:
        """Manual reset (e.g. after engine restart)."""
        self.long_ema_al = 0.0
        self.recent_window.clear()
        self.tripped = False
        self.trip_reason = None

    def state_dict(self) -> dict:
        return {
            "long_ema_al": self.long_ema_al,
            "window_len": len(self.recent_window),
            "window_avg": (
                sum(self.recent_window) / len(self.recent_window)
                if self.recent_window
                else 0.0
            ),
            "tripped": self.tripped,
            "trip_reason": self.trip_reason,
            "trip_count": self.trip_count,
        }


# ═══════════════════════════════════════════════════════════════════
# Sub-kernel B: Persistent K/V buffer pool (DFlash-specific MVP)
# ═══════════════════════════════════════════════════════════════════

_ENV_SUB_B = "GENESIS_PN40_ENABLE_SUB_B"


def sub_b_enabled() -> bool:
    if not env_enabled():
        return False
    val = os.environ.get(_ENV_SUB_B, "").strip().lower()
    if val in ("0", "false", "no", "off"):
        return False
    return True


class PersistentKVBufferPool:
    """Per-shape buffer pool for drafter K/V allocations.

    Saves `cudaMalloc` overhead by reusing same allocation across draft
    steps when shape is stable. Bounded size (LRU eviction) to prevent
    leaks under shape churn.

    Universal API; current orchestrator wires only DFlash path. MTP path
    via torch.compile already optimizes allocations — wiring there gives
    no extra benefit (verified empirically on Qwen3.6 MTP).
    """

    def __init__(self, max_entries_per_shape: int = 4, max_distinct_shapes: int = 16):
        self._pool: dict[tuple, list] = {}  # (shape, dtype) → [tensor, ...]
        self._lru: list[tuple] = []
        self.max_entries = max_entries_per_shape
        self.max_shapes = max_distinct_shapes
        self.hits = 0
        self.misses = 0

    def _key(self, shape, dtype, device):
        return (tuple(shape), str(dtype), str(device))

    def get(self, shape, dtype, device):
        """Return a buffer matching shape+dtype+device, or None."""
        import torch  # noqa: F401

        if not sub_b_enabled():
            return None
        k = self._key(shape, dtype, device)
        bucket = self._pool.get(k)
        if bucket:
            self.hits += 1
            # Update LRU
            if k in self._lru:
                self._lru.remove(k)
            self._lru.append(k)
            return bucket.pop()
        self.misses += 1
        return None

    def put(self, tensor) -> None:
        """Return a tensor to the pool. Bounded by max_entries + max_shapes."""
        if not sub_b_enabled():
            return
        k = self._key(tensor.shape, tensor.dtype, tensor.device)
        bucket = self._pool.setdefault(k, [])
        if len(bucket) >= self.max_entries:
            return  # silently drop — already enough buffered
        bucket.append(tensor)
        if k not in self._lru:
            self._lru.append(k)
            # Evict LRU shape if exceed total
            while len(self._lru) > self.max_shapes:
                evict = self._lru.pop(0)
                self._pool.pop(evict, None)

    def stats(self) -> dict:
        total = self.hits + self.misses
        return {
            "hits": self.hits,
            "misses": self.misses,
            "hit_rate": self.hits / total if total > 0 else 0.0,
            "distinct_shapes": len(self._lru),
            "total_buffered": sum(len(v) for v in self._pool.values()),
        }

    def clear(self) -> None:
        self._pool.clear()
        self._lru.clear()
        self.hits = 0
        self.misses = 0


# Module-level singleton for sub-B
_BUFFER_POOL = PersistentKVBufferPool()


def get_buffer_pool() -> PersistentKVBufferPool:
    return _BUFFER_POOL


# ═══════════════════════════════════════════════════════════════════
# Orchestrator API (used by wiring + bench tools)
# ═══════════════════════════════════════════════════════════════════


def orchestrator_status() -> dict:
    """Return current state of all PN40 sub-kernels for diagnostics."""
    return {
        "master_enabled": env_enabled(),
        "sub_a_enabled": sub_a_enabled(),
        "sub_b_enabled": sub_b_enabled(),
        "sub_c_enabled": sub_c_enabled(),
        "sub_d_enabled": sub_d_enabled(),
        "buffer_pool": _BUFFER_POOL.stats(),
        "controllers": {
            method: ctl.state_dict()
            for method, ctl in _CONTROLLERS.items()
        },
        "sentinels": {
            method: sent.state_dict()
            for method, sent in _SENTINELS.items()
        },
    }


# ═══════════════════════════════════════════════════════════════════
# Universal MTP/DFlash observability hooks (v1: observe-only)
# Wires sub-C controller + sub-D sentinel to scheduler accepted-length
# feedback loop. Runtime K override deferred to v2 (requires proposer
# rewrite). v1 logs adaptive recommendations + flags anomalies.
# ═══════════════════════════════════════════════════════════════════


_CONTROLLERS: dict[str, AdaptiveSpecKController] = {}
_SENTINELS: dict[str, StabilitySentinel] = {}
_OBSERVATION_LOG_INTERVAL = 200  # log aggregate stats every N observations
_OBSERVATION_COUNTERS: dict[str, int] = {}


def _ensure_controller(spec_method: str, base_k: int) -> AdaptiveSpecKController:
    """Lazy-init per-spec_method controller. Idempotent."""
    if spec_method not in _CONTROLLERS:
        tiers = get_default_tiers(spec_method, base_k)
        _CONTROLLERS[spec_method] = AdaptiveSpecKController(
            tiers=tiers, base_k=base_k,
        )
    return _CONTROLLERS[spec_method]


def _ensure_sentinel(spec_method: str) -> StabilitySentinel:
    """Lazy-init per-spec_method sentinel. Idempotent."""
    if spec_method not in _SENTINELS:
        _SENTINELS[spec_method] = StabilitySentinel()
    return _SENTINELS[spec_method]


def pn40_observe_accepted_len(
    spec_method: str,
    accepted_len: int | float,
    base_k: int = 3,
) -> None:
    """Universal hook called from scheduler after each spec-decode step.

    Feeds accepted_len to BOTH the adaptive K controller and the stability
    sentinel for the given spec_method. Defensive — never raises (called
    from the engine hot path).

    Args:
        spec_method: "mtp", "dflash", "ngram", etc. (matches vllm config)
        accepted_len: number of accepted spec tokens this step
        base_k: configured K (fallback if controller not yet init'd)

    v1 is observe-only: controllers compute recommended K but the engine
    does NOT use it (proposer-level override is v2 work). Sentinel trips
    on anomalies and logs WARNING.
    """
    if not env_enabled():
        return
    try:
        if sub_c_enabled():
            ctl = _ensure_controller(spec_method, base_k)
            ctl.observe(float(accepted_len))
        if sub_d_enabled():
            sent = _ensure_sentinel(spec_method)
            tripped = sent.observe(float(accepted_len))
            if tripped:
                log.warning(
                    "[PN40 sub-D sentinel] %s tripped: %s",
                    spec_method, sent.trip_reason,
                )
                # Sentinel-driven auto-disable bridge: cascade into
                # sub-kernel C+D registries so future requests bypass
                # PN40 paths and use baseline behavior. Sub-A stays on
                # (independent kernel-level signal).
                _check_and_auto_disable_on_trip(spec_method)

        # Periodic stats log (low overhead — every 200 observations)
        cnt = _OBSERVATION_COUNTERS.get(spec_method, 0) + 1
        _OBSERVATION_COUNTERS[spec_method] = cnt
        if cnt % _OBSERVATION_LOG_INTERVAL == 0:
            ctl_state = (
                _CONTROLLERS[spec_method].state_dict()
                if spec_method in _CONTROLLERS else None
            )
            sent_state = (
                _SENTINELS[spec_method].state_dict()
                if spec_method in _SENTINELS else None
            )
            log.info(
                "[PN40 observe %s] count=%d controller=%s sentinel=%s",
                spec_method, cnt,
                ctl_state, sent_state,
            )
    except Exception as e:  # noqa: BLE001 — never break engine
        log.debug("[PN40 observe] suppressed exception: %s", e)


def pn40_get_recommended_k(
    spec_method: str,
    base_k: int,
    workload_class: str | None = None,
) -> int:
    """Get current adaptive K recommendation for spec_method.

    v3 (workload-aware): if workload_class is provided, controller biases
    its tier choice (code=+1 tier, long_ctx=-1 tier, others=neutral).
    See AdaptiveSpecKController._workload_bias_table for full mapping.

    v2 semantics retained: respects auto-disable; falls back to base_k
    if sentinel-disabled or controller not initialized.
    """
    if not env_enabled() or not sub_c_enabled():
        return base_k
    if is_auto_disabled("C"):
        return base_k
    if spec_method not in _CONTROLLERS:
        return base_k
    ctl = _CONTROLLERS[spec_method]
    # Apply per-request workload bias (cheap; no allocation)
    if workload_class is not None:
        ctl.set_workload_class(workload_class)
    return ctl.current_k()


def pn40_should_disable_for_request(spec_method: str) -> bool:
    """Check if downstream PN40 paths should bypass for this spec_method.

    Returns True if EITHER:
      - sub-D auto-disabled this method (sentinel tripped), OR
      - the per-method sentinel itself is tripped (covers cold-init case
        before auto_disable cascade fires)

    v2: orchestrator-level decision point. Wiring patches that read
    request._genesis_pn40_workload_class can short-circuit on True.
    """
    if not env_enabled() or not sub_d_enabled():
        return False
    if is_auto_disabled("D"):
        return True
    sent = _SENTINELS.get(spec_method)
    return sent is not None and sent.tripped


def reset_sentinels() -> None:
    """Reset all per-spec_method sentinels. Call after engine restart or
    when operator manually accepts that anomaly is resolved."""
    for sent in _SENTINELS.values():
        sent.reset()


def reset_controllers() -> None:
    """Reset all controllers to base_k. For testing/operator override."""
    _CONTROLLERS.clear()
    _OBSERVATION_COUNTERS.clear()


# ═══════════════════════════════════════════════════════════════════
# Sentinel-driven auto-disable bridge (v2 item)
# Single decision point used by all PN40 sub-kernels: if sentinel for
# this spec_method has tripped, downstream code paths short-circuit
# back to baseline behavior (no PN40 optimizations) until manual reset.
# ═══════════════════════════════════════════════════════════════════


# Module-level flags — checked by sub-kernels' eligibility predicates.
# Allows orchestrator to disable a sub-kernel per-method WITHOUT requiring
# every wiring patch to know about sentinel state.
#
# Audit P1.6 fix 2026-05-05 (genesis_deep_cross_audit_2026-05-05, A-11):
# Previously stored sub_name only — a sentinel trip on MTP would disable
# C+D for ALL methods including DFlash. Refactored to (spec_method, sub_name)
# tuples so trips are scoped to the originating method. Backwards-compat
# helpers `is_auto_disabled(sub_name)` and `auto_disable_sub_kernel(sub_name,
# reason)` are preserved as wrappers over the per-method primitive.
_AUTO_DISABLED_PER_METHOD: set[tuple[str, str]] = set()


def auto_disable_sub_kernel_for_method(
    spec_method: str, sub_name: str, reason: str,
) -> None:
    """Programmatically auto-disable a sub-kernel for ONE spec method.

    Audit P1.6 primitive (genesis_deep_cross_audit). Other methods stay
    enabled. Sub-names: "A", "B", "C", "D" (per omnibus design).
    Idempotent (no-op if already disabled for this method).
    """
    key = (spec_method, sub_name)
    if key in _AUTO_DISABLED_PER_METHOD:
        return
    _AUTO_DISABLED_PER_METHOD.add(key)
    log.warning(
        "[PN40 auto-disable] sub-%s disabled for %s: %s. Other spec methods "
        "unaffected. Manual reset via "
        "vllm._genesis.kernels.pn40_dflash_omnibus.reset_auto_disable() "
        "to re-engage all.",
        sub_name, spec_method, reason,
    )


def auto_disable_sub_kernel(sub_name: str, reason: str) -> None:
    """Backwards-compat shim: applies disable to ALL known spec methods.

    Pre-A-11 fix this was the only entry point and silently global. New
    code should call `auto_disable_sub_kernel_for_method(method, sub_name, reason)`
    instead. This wrapper is kept so existing tests / call sites compile.
    """
    for method in ("mtp", "dflash", "ngram", "eagle"):
        auto_disable_sub_kernel_for_method(method, sub_name, reason)


def is_auto_disabled(sub_name: str, spec_method: str | None = None) -> bool:
    """Read-only check used by sub-kernel eligibility predicates.

    If `spec_method` is None (legacy callers), returns True iff the sub-kernel
    is disabled for ANY method (preserving pre-A-11 behavior). New callers
    SHOULD pass the spec_method to get per-method scoping.
    """
    if spec_method is not None:
        return (spec_method, sub_name) in _AUTO_DISABLED_PER_METHOD
    # Legacy global semantics — answers "is sub_name disabled anywhere?"
    return any(s == sub_name for (_m, s) in _AUTO_DISABLED_PER_METHOD)


def is_auto_disabled_for_method(spec_method: str, sub_name: str) -> bool:
    """Per-method check (audit P1.6 primitive). Strict (spec_method, sub_name)."""
    return (spec_method, sub_name) in _AUTO_DISABLED_PER_METHOD


def reset_auto_disable() -> None:
    """Operator-only reset of all sentinel-triggered disables.

    Use case: AL drop was a transient blip (e.g. cold-cache compile),
    sentinel false-tripped, want to re-engage PN40 without engine restart.
    """
    if _AUTO_DISABLED_PER_METHOD:
        log.info(
            "[PN40] reset_auto_disable: re-engaging %d (method, sub) entries: %s",
            len(_AUTO_DISABLED_PER_METHOD),
            sorted(_AUTO_DISABLED_PER_METHOD),
        )
    _AUTO_DISABLED_PER_METHOD.clear()
    # Also reset the sentinels themselves so they observe fresh baseline.
    reset_sentinels()


def _check_and_auto_disable_on_trip(spec_method: str) -> None:
    """Internal: called from observe loop. If sentinel for this method
    just tripped, auto-disable the corresponding sub-kernels FOR THIS
    METHOD ONLY (audit P1.6 fix — was global pre-2026-05-05).

    Mapping: trip on MTP → disable C+D for MTP only (DFlash unaffected).
            trip on DFlash → disable C+D for DFlash only; A keeps running.
    """
    sent = _SENTINELS.get(spec_method)
    if sent is None or not sent.tripped:
        return
    # Conservative: disable C + D for this method's request path only.
    # Sub-A (kernel-level) is independent — leave it on.
    auto_disable_sub_kernel_for_method(
        spec_method, "C",
        f"sentinel tripped on {spec_method}: {sent.trip_reason}",
    )
    auto_disable_sub_kernel_for_method(
        spec_method, "D",
        f"sentinel tripped on {spec_method}: {sent.trip_reason}",
    )
