# SPDX-License-Identifier: Apache-2.0
"""requant_inplace — FP8 E4M3 -> INT8 diádico **sobre el mismo buffer**.

Por qué existe
--------------
La conversión anterior materializaba **cuatro copias completas** del peso por
capa, todas vivas a la vez:

  1. ``w_fp8_orig`` [N,K] original
  2. ``w_fp8_orig.t().contiguous()`` — transpuesta fp8
  3. ``w_int8`` [K,N] que sale del requantizador
  4. ``b_col.copy_(w_int8)`` — otra vez, a column-major

Y ``process_weights_after_loading`` corre dentro del pool ``weights`` del
asignador cumem, donde **lo liberado no se devuelve** hasta salir del contexto.
Con 12.17 GB de pesos por rank quedaban retenidos ~24 GB sobre los 23.56 de una
3090, y el arranque moría con ``CUDA Error: out of memory at
cumem_allocator.cpp:163``.

La observación que elimina las cuatro copias:

    empty_strided((K, N), (1, K))  ==  [N, K] contiguo, transpuesto

Son los mismos bytes en el mismo orden, y ``w_fp8_orig`` **ya** es [N,K]
contiguo. Como FP8 e INT8 miden 1 byte, ``w.view(torch.int8).t()`` es
exactamente el ``b_col`` [K,N] column-major que esperan los super kernels,
compartiendo storage. Y como la cuantización es elementwise (tras una pasada de
amax que sólo lee), el INT8 se escribe **encima** del FP8.

Resultado: 4x -> 1x. El peso original y el nuevo son el mismo tensor.

Decodificación de E4M3 sin FP8 nativo
-------------------------------------
sm_86 **no** tiene FP8 en Triton::

    ValueError: type fp8e4nv not supported in this architecture.
                The supported fp8 dtypes are ('fp8e4b15', 'fp8e5')

Así que el byte se lee como entero y se decodifica a mano::

    signo    = bits & 0x80
    exp      = (bits >> 3) & 0x0F
    mantisa  = bits & 0x07
    m_int    = mantisa + (8 si exp != 0 else 0)     # el 1 implícito
    valor    = ±m_int * 2^(max(exp, 1) - 10)

``max(exp,1)-10`` cubre normales y subnormales con la misma expresión: para
exp=0 y exp=1 el exponente es -9, que es la propiedad estándar de los
subnormales. Todo entero salvo el ``exp2`` final.

Los kernels no validan nada: se asume comprobado aguas arriba.
"""

from __future__ import annotations

import torch
import triton
import triton.language as tl

try:
    from vllm._genesis.kernels.ptx_runtime import KernelNativo
    from vllm._genesis.kernels.ptx_runtime import habilitado as _ptx_habilitado
except ImportError:  # uso suelto (tests fuera del paquete)
    from ptx_runtime import KernelNativo
    from ptx_runtime import habilitado as _ptx_habilitado

SHIFT_BLOCK: int = 128

# PTX editado (E1) de ``_quant_inplace_triton``, horneado con
# ``BN_BLK=128, BK=128`` y strides unitarios en la dim K de scale_inv/shift.
# Gate bit-exacto (3 semillas) contra el JIT de Triton: /tmp/opencode/tests_ptx/.
_PTX_REQUANT_QUANT = r'''//
// Generated by LLVM NVPTX Back-End
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	_quant_inplace_kernel   // -- Begin function _quant_inplace_kernel
.global .align 1 .b8 _$_str[11] = {95, 95, 67, 85, 68, 65, 95, 70, 84, 90};
                                        // @_quant_inplace_kernel
.visible .entry _quant_inplace_kernel(
	.param .u64 .ptr .global .align 1 _quant_inplace_kernel_param_0,
	.param .u64 .ptr .global .align 1 _quant_inplace_kernel_param_1,
	.param .u64 .ptr .global .align 1 _quant_inplace_kernel_param_2,
	.param .u64 .ptr .global .align 1 _quant_inplace_kernel_param_3,
	.param .u64 .ptr .global .align 1 _quant_inplace_kernel_param_4,
	.param .u32 _quant_inplace_kernel_param_5,
	.param .u32 _quant_inplace_kernel_param_6,
	.param .u32 _quant_inplace_kernel_param_7,
	.param .u64 .ptr .global .align 1 _quant_inplace_kernel_param_8,
	.param .u64 .ptr .global .align 1 _quant_inplace_kernel_param_9
)
.reqntid 128
{
	.reg .pred 	%p<4>;
	.reg .b16 	%rs<5>;
	.reg .b32 	%r<40>;
	.reg .b64 	%rd<15>;
	.loc	1 89 0                          // requant_inplace.py:89:0
$L__func_begin0:
	.loc	1 89 0                          // requant_inplace.py:89:0

// %bb.0:                               // %__nv_exp2f.exit
	ld.param.b64 	%rd6, [_quant_inplace_kernel_param_0];
	ld.param.b64 	%rd7, [_quant_inplace_kernel_param_1];
$L__tmp0:
	.loc	1 99 22                         // requant_inplace.py:99:22
	mov.u32 	%r4, %ctaid.x;
	ld.param.b64 	%rd8, [_quant_inplace_kernel_param_2];
	.loc	1 100 23                        // requant_inplace.py:100:23
	mov.u32 	%r5, %ctaid.y;
	ld.param.b64 	%rd9, [_quant_inplace_kernel_param_3];
	.loc	1 101 24                        // requant_inplace.py:101:24
	mov.u32 	%r6, %tid.x;
	and.b32 	%r7, %r6, 127;
	ld.param.b64 	%rd10, [_quant_inplace_kernel_param_4];
	ld.param.b32 	%r8, [_quant_inplace_kernel_param_5];
	.loc	1 102 32                        // requant_inplace.py:102:32
	shl.b32 	%r9, %r5, 7;
	ld.param.b32 	%r10, [_quant_inplace_kernel_param_6];
	.loc	1 102 27                        // requant_inplace.py:102:27
	or.b32 	%r11, %r7, %r9;
	ld.param.b32 	%r12, [_quant_inplace_kernel_param_7];
	.loc	1 102 37                        // requant_inplace.py:102:37
	mad.lo.s32 	%r13, %r8, %r4, %r11;
	.loc	1 103 42                        // requant_inplace.py:103:42
	cvt.s64.s32 	%rd11, %r13;
	add.s64 	%rd1, %rd6, %rd11;
	.loc	1 103 34                        // requant_inplace.py:103:34
	// begin inline asm
	mov.u16 %rs1, 0x0;
	ld.global.b8 { %rs1 }, [ %rd1 + 0 ];
	// end inline asm
	cvt.s16.s8 	%rs3, %rs1;
$L__tmp1:
	.loc	1 66 16                         // requant_inplace.py:66:16 @[ requant_inplace.py:103:26 ]
	cvt.u32.u16 	%r14, %rs1;
	shr.u16 	%rs4, %rs1, 3;
	.loc	1 68 16                         // requant_inplace.py:68:16 @[ requant_inplace.py:103:26 ]
	cvt.u32.u16 	%r15, %rs4;
	.loc	1 68 21                         // requant_inplace.py:68:21 @[ requant_inplace.py:103:26 ]
	and.b32 	%r16, %r15, 15;
	.loc	1 70 67                         // requant_inplace.py:70:67 @[ requant_inplace.py:103:26 ]
	max.u32 	%r17, %r16, 1;
	.loc	1 70 72                         // requant_inplace.py:70:72 @[ requant_inplace.py:103:26 ]
	add.s32 	%r18, %r17, -10;
	.loc	1 70 79                         // requant_inplace.py:70:79 @[ requant_inplace.py:103:26 ]
	cvt.rn.f32.s32 	%r19, %r18;
	.loc	1 70 50                         // requant_inplace.py:70:50 @[ requant_inplace.py:103:26 ]
	ex2.approx.ftz.f32 	%r20, %r19;
$L__tmp2:
	.loc	1 104 34                        // requant_inplace.py:104:34
	shr.u32 	%r21, %r4, 7;
	.loc	1 104 44                        // requant_inplace.py:104:44
	mul.lo.s32 	%r22, %r10, %r21;
	.loc	1 104 28                        // requant_inplace.py:104:28
	mad.wide.s32 	%rd12, %r22, 4, %rd8;
	.loc	1 104 56                        // requant_inplace.py:104:56
	mul.wide.u32 	%rd13, %r5, 4;
	add.s64 	%rd2, %rd12, %rd13;
	.loc	1 104 16                        // requant_inplace.py:104:16
	// begin inline asm
	mov.u32 %r1, 0x0;
	ld.global.b32 { %r1 }, [ %rd2 + 0 ];
	// end inline asm
	.loc	1 105 31                        // requant_inplace.py:105:31
	mad.wide.u32 	%rd3, %r4, 4, %rd9;
	.loc	1 105 19                        // requant_inplace.py:105:19
	// begin inline asm
	mov.u32 %r2, 0x0;
	ld.global.b32 { %r2 }, [ %rd3 + 0 ];
	// end inline asm
	.loc	1 106 44                        // requant_inplace.py:106:44
	mul.lo.s32 	%r23, %r12, %r21;
	.loc	1 106 28                        // requant_inplace.py:106:28
	mad.wide.s32 	%rd14, %r23, 4, %rd10;
	.loc	1 106 57                        // requant_inplace.py:106:57
	add.s64 	%rd4, %rd14, %rd13;
	.loc	1 106 16                        // requant_inplace.py:106:16
	// begin inline asm
	mov.u32 %r3, 0x0;
	ld.global.b32 { %r3 }, [ %rd4 + 0 ];
	// end inline asm
	.loc	1 106 8                         // requant_inplace.py:106:8
	ex2.approx.ftz.f32 	%r24, %r3;
$L__tmp3:
	.loc	1 67 26                         // requant_inplace.py:67:26 @[ requant_inplace.py:103:26 ]
	setp.lt.s16 	%p1, %rs3, 0;
	.loc	1 69 17                         // requant_inplace.py:69:17 @[ requant_inplace.py:103:26 ]
	and.b32 	%r25, %r14, 7;
	.loc	1 69 41                         // requant_inplace.py:69:41 @[ requant_inplace.py:103:26 ]
	setp.eq.b32 	%p2, %r16, 0;
	.loc	1 69 47                         // requant_inplace.py:69:47 @[ requant_inplace.py:103:26 ]
	selp.b32 	%r26, 0, 8, %p2;
	.loc	1 69 25                         // requant_inplace.py:69:25 @[ requant_inplace.py:103:26 ]
	or.b32 	%r27, %r26, %r25;
	.loc	1 70 28                         // requant_inplace.py:70:28 @[ requant_inplace.py:103:26 ]
	cvt.rn.f32.u32 	%r28, %r27;
	.loc	1 70 19                         // requant_inplace.py:70:19 @[ requant_inplace.py:103:26 ]
	neg.f32 	%r29, %r28;
	selp.f32 	%r30, %r29, %r28, %p1;
	.loc	1 70 42                         // requant_inplace.py:70:42 @[ requant_inplace.py:103:26 ]
	mul.f32 	%r31, %r30, %r20;
$L__tmp4:
	.loc	1 105 36                        // requant_inplace.py:105:36
	mul.f32 	%r32, %r24, %r2;
	.loc	1 107 12                        // requant_inplace.py:107:12
	mul.f32 	%r33, %r31, %r1;
	.loc	1 107 16                        // requant_inplace.py:107:16
	div.full.f32 	%r34, %r33, %r32;
	.loc	1 108 27                        // requant_inplace.py:108:27
	.loc	1 108 37                        // requant_inplace.py:108:37
	lop3.b32 	%r35, 0x3f000000, %r34, 0x80000000, 0xF8;
	.loc	1 108 13                        // requant_inplace.py:108:13
	add.f32 	%r36, %r34, %r35;
	.loc	1 108 47                        // requant_inplace.py:108:47
	cvt.rzi.s32.f32 	%r37, %r36;
	.loc	1 109 21                        // requant_inplace.py:109:21
	add.s64 	%rd5, %rd7, %rd11;
	.loc	1 109 52                        // requant_inplace.py:109:52
	max.s32 	%r38, %r37, -127;
	.loc	1 109 59                        // requant_inplace.py:109:59
	min.s32 	%r39, %r38, 127;
	.loc	1 109 27                        // requant_inplace.py:109:27
	cvt.u16.u32 	%rs2, %r39;
	// begin inline asm
	st.global.b8 [ %rd5 + 0 ], { %rs2 };
	// end inline asm
	.loc	1 109 4                         // requant_inplace.py:109:4
	ret;
$L__tmp5:
$L__func_end0:
                                        // -- End function
}
	.file	1 "/home/usuario/Proyectos/genesis-vllm-patches/vllm/_genesis/kernels/requant_inplace.py"
	.section	.debug_abbrev
	{
.b8 1                                   // Abbreviation Code
.b8 17                                  // DW_TAG_compile_unit
.b8 1                                   // DW_CHILDREN_yes
.b8 37                                  // DW_AT_producer
.b8 8                                   // DW_FORM_string
.b8 19                                  // DW_AT_language
.b8 5                                   // DW_FORM_data2
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 16                                  // DW_AT_stmt_list
.b8 6                                   // DW_FORM_data4
.b8 27                                  // DW_AT_comp_dir
.b8 8                                   // DW_FORM_string
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 2                                   // Abbreviation Code
.b8 46                                  // DW_TAG_subprogram
.b8 0                                   // DW_CHILDREN_no
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 32                                  // DW_AT_inline
.b8 11                                  // DW_FORM_data1
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 3                                   // Abbreviation Code
.b8 46                                  // DW_TAG_subprogram
.b8 1                                   // DW_CHILDREN_yes
.b8 17                                  // DW_AT_low_pc
.b8 1                                   // DW_FORM_addr
.b8 18                                  // DW_AT_high_pc
.b8 1                                   // DW_FORM_addr
.b8 49                                  // DW_AT_abstract_origin
.b8 19                                  // DW_FORM_ref4
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 4                                   // Abbreviation Code
.b8 29                                  // DW_TAG_inlined_subroutine
.b8 0                                   // DW_CHILDREN_no
.b8 49                                  // DW_AT_abstract_origin
.b8 19                                  // DW_FORM_ref4
.b8 17                                  // DW_AT_low_pc
.b8 1                                   // DW_FORM_addr
.b8 18                                  // DW_AT_high_pc
.b8 1                                   // DW_FORM_addr
.b8 88                                  // DW_AT_call_file
.b8 11                                  // DW_FORM_data1
.b8 89                                  // DW_AT_call_line
.b8 11                                  // DW_FORM_data1
.b8 87                                  // DW_AT_call_column
.b8 11                                  // DW_FORM_data1
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 0                                   // EOM(3)
	}
	.section	.debug_info
	{
.b32 178                                // Length of Unit
.b8 2                                   // DWARF version number
.b8 0
.b32 .debug_abbrev                      // Offset Into Abbrev. Section
.b8 8                                   // Address Size (in bytes)
.b8 1                                   // Abbrev [1] 0xb:0xab DW_TAG_compile_unit
.b8 116                                 // DW_AT_producer
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2                                   // DW_AT_language
.b8 0
.b8 114                                 // DW_AT_name
.b8 101
.b8 113
.b8 117
.b8 97
.b8 110
.b8 116
.b8 95
.b8 105
.b8 110
.b8 112
.b8 108
.b8 97
.b8 99
.b8 101
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line                        // DW_AT_stmt_list
.b8 47                                  // DW_AT_comp_dir
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 117
.b8 115
.b8 117
.b8 97
.b8 114
.b8 105
.b8 111
.b8 47
.b8 80
.b8 114
.b8 111
.b8 121
.b8 101
.b8 99
.b8 116
.b8 111
.b8 115
.b8 47
.b8 103
.b8 101
.b8 110
.b8 101
.b8 115
.b8 105
.b8 115
.b8 45
.b8 118
.b8 108
.b8 108
.b8 109
.b8 45
.b8 112
.b8 97
.b8 116
.b8 99
.b8 104
.b8 101
.b8 115
.b8 47
.b8 118
.b8 108
.b8 108
.b8 109
.b8 47
.b8 95
.b8 103
.b8 101
.b8 110
.b8 101
.b8 115
.b8 105
.b8 115
.b8 47
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 115
.b8 0
.b8 2                                   // Abbrev [2] 0x6f:0x18 DW_TAG_subprogram
.b8 95                                  // DW_AT_name
.b8 113
.b8 117
.b8 97
.b8 110
.b8 116
.b8 95
.b8 105
.b8 110
.b8 112
.b8 108
.b8 97
.b8 99
.b8 101
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 0
.b8 1                                   // DW_AT_inline
.b8 3                                   // Abbrev [3] 0x87:0x2e DW_TAG_subprogram
.b64 $L__func_begin0                    // DW_AT_low_pc
.b64 $L__func_end0                      // DW_AT_high_pc
.b32 111                                // DW_AT_abstract_origin
.b8 4                                   // Abbrev [4] 0x9c:0x18 DW_TAG_inlined_subroutine
.b32 111                                // DW_AT_abstract_origin
.b64 $L__tmp1                           // DW_AT_low_pc
.b64 $L__tmp4                           // DW_AT_high_pc
.b8 1                                   // DW_AT_call_file
.b8 103                                 // DW_AT_call_line
.b8 26                                  // DW_AT_call_column
.b8 0                                   // End Of Children Mark
.b8 0                                   // End Of Children Mark
	}
	.section	.debug_macinfo	{	}
'''

_PTQ_KERNEL = KernelNativo(
    "C/requant_quant_inplace", _PTX_REQUANT_QUANT,
    num_warps=4, shared=0,
    idx=[0, 1, 2, 3, 4, 5, 6, 8], n_runtime=8,
    horneado={7: 1, 9: 1, 10: 128, 11: 128},
)


@triton.jit
def _decodificar_e4m3(bits):
    """Bits de FP8 E4M3 (leídos como int8) -> valor fp32. Sin FP8 nativo."""
    b = bits.to(tl.int32) & 0xFF
    signo = tl.where(b >= 128, -1.0, 1.0)
    exp = (b >> 3) & 0x0F
    m_int = (b & 0x07) + tl.where(exp != 0, 8, 0)
    return signo * m_int.to(tl.float32) * tl.exp2((tl.maximum(exp, 1) - 10).to(tl.float32))


@triton.jit
def _amax_por_bloque_kernel(
    w_ptr, s_inv_ptr, out_ptr,
    stride_wn, stride_sn, stride_sk, stride_on,
    BN_BLK: tl.constexpr, BK: tl.constexpr,
):
    """amax de |peso real| por (fila n, bloque de K) -> ``out`` [N, Kb] fp32."""
    n = tl.program_id(0)
    kb = tl.program_id(1)
    offs = tl.arange(0, BK)
    v = _decodificar_e4m3(tl.load(w_ptr + n * stride_wn + kb * BK + offs))
    s = tl.load(s_inv_ptr + (n // BN_BLK) * stride_sn + kb * stride_sk)
    tl.store(out_ptr + n * stride_on + kb, tl.max(tl.abs(v)) * s)


@triton.jit
def _quant_inplace_triton(
    w_ptr, q_ptr, s_inv_ptr, s_row_ptr, shift_ptr,
    stride_wn, stride_sn, stride_sk, stride_shn, stride_shk,
    BN_BLK: tl.constexpr, BK: tl.constexpr,
):
    """Escribe el INT8 **sobre los mismos bytes** que ocupaba el FP8.

    Cada programa toca ``[n, kb*BK : (kb+1)*BK]``, rangos disjuntos entre
    programas, y lee antes de escribir dentro del programa: in-place seguro.
    """
    n = tl.program_id(0)
    kb = tl.program_id(1)
    offs = tl.arange(0, BK)
    base = n * stride_wn + kb * BK + offs
    v = _decodificar_e4m3(tl.load(w_ptr + base))
    s = tl.load(s_inv_ptr + (n // BN_BLK) * stride_sn + kb * stride_sk)
    paso = tl.load(s_row_ptr + n) * tl.exp2(
        tl.load(shift_ptr + (n // BN_BLK) * stride_shn + kb * stride_shk).to(tl.float32))
    x = v * s / paso
    q = (x + tl.where(x >= 0.0, 0.5, -0.5)).to(tl.int32)
    tl.store(q_ptr + base, tl.minimum(tl.maximum(q, -127), 127).to(tl.int8))


# Compat harness/tests: nombre histórico del cuerpo Triton (solo referencia).
_quant_inplace_kernel = _quant_inplace_triton


def requantizar_fp8_a_int8_inplace(
    w_fp8: torch.Tensor,
    scale_inv: torch.Tensor,
    block_size: tuple[int, int] = (128, 128),
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """FP8 [N,K] -> INT8 diádico in-place.

    :param w_fp8: peso [N,K] ``float8_e4m3fn`` contiguo. **Se sobrescribe.**
    :param scale_inv: escalas por bloque [N/Bn, K/Bk] fp32.
    :param block_size: (Bk, Bn).
    :returns: ``(b_col, w_scales, w_shifts)`` donde ``b_col`` es una **vista**
        int8 [K,N] column-major del mismo storage que ``w_fp8``, ``w_scales`` es
        [N,1] fp32 y ``w_shifts`` es [Kb, Nb] int8 con el layout que esperan los
        super kernels.
    """
    bk, bn = block_size
    n, k = w_fp8.shape
    kb_n, nb_n = k // bk, n // bn
    dev = w_fp8.device
    bits = w_fp8.view(torch.int8)

    # Pasada 1 — sólo lee. amax del peso real por (fila, bloque de K).
    amax_nk = torch.empty((n, kb_n), dtype=torch.float32, device=dev)
    _amax_por_bloque_kernel[(n, kb_n)](
        bits, scale_inv, amax_nk,
        bits.stride(0), scale_inv.stride(0), scale_inv.stride(1), amax_nk.stride(0),
        BN_BLK=bn, BK=bk, num_warps=4, num_stages=1,
    )

    # Escala por canal de salida y shift diádico por bloque. Todo sobre
    # tensores [N, Kb] = 2.8 MB, no sobre el peso.
    s_row = (amax_nk.amax(dim=1) / 127.0).clamp(min=1e-30)              # [N]
    need = torch.log2((amax_nk / (127.0 * s_row[:, None])).clamp(min=1e-30))
    shift = torch.ceil(need.reshape(nb_n, bn, kb_n).amax(dim=1)).clamp(-10.0, 10.0)

    # Pasada 2 — escribe INT8 encima del FP8.
    if (_ptx_habilitado() and bk == 128 and bn == 128
            and scale_inv.stride(1) == 1 and shift.stride(1) == 1):
        # Camino nativo: args en EXACTO orden de declaracion (constexpr
        # inline). El cubin lleva horneados stride_sk=1, stride_shk=1,
        # BN_BLK=128 y BK=128 (guardados arriba). Grid (n, kb_n), 4 warps.
        _PTQ_KERNEL((n, kb_n), bits, bits, scale_inv, s_row, shift,
                    bits.stride(0), scale_inv.stride(0), scale_inv.stride(1),
                    shift.stride(0), shift.stride(1), bn, bk)
    else:
        _quant_inplace_triton[(n, kb_n)](
            bits, bits, scale_inv, s_row, shift,
            bits.stride(0), scale_inv.stride(0), scale_inv.stride(1),
            shift.stride(0), shift.stride(1),
            BN_BLK=bn, BK=bk, num_warps=4, num_stages=1,
        )

    # b_col: misma memoria, sólo strides. [K,N] con stride (1,K).
    return bits.t(), s_row.unsqueeze(1).contiguous(), shift.t().contiguous().to(torch.int8)


__all__ = ["requantizar_fp8_a_int8_inplace", "SHIFT_BLOCK"]
