# SPDX-License-Identifier: Apache-2.0
"""SK-04 W4A8 — FA_O_W4A8 — capa completa Full-Attention o_proj (RowParallel) en INT4/INT8.

Capa completa: quant per-token -> GEMM W4A8 con residual fusionado en el
epílogo -> all_reduce. Geometría per-rank TP=2: K=3072, N=5120.

Convención W4A8 (única para toda la familia SK-*_w4a8)
------------------------------------------------------
``w_packed`` ``[K/2, N]`` int8: cada byte lleva dos pesos de 4 bits, el de
``k=2i`` en el nibble bajo y el de ``k=2i+1`` en el alto, con zero-point 8.
``w_scales`` ``[K/128, N]`` fp32: una escala por grupo de 128 filas (GPTQ).
Activación INT8 per-token con su escala ``[M]`` fp32.

Qué cambió respecto de la versión anterior
------------------------------------------
El desempaquetado leía **cada byte dos veces** —una para el nibble par y otra
para el impar— y descartaba la mitad en cada lectura::

    packed_k = cur_k // 2
    is_even  = (cur_k % 2) == 0
    packed   = tl.load(w_packed_ptrs, ...)      # el byte entero
    w_q      = tl.where(is_even[:, None], packed & 15, (packed >> 4) & 15)

Eso da exactamente el mismo tráfico de memoria que INT8: **el ahorro de ancho
de banda de W4, que es el único motivo para hacer W4A8, desaparecía**. Ahora el
byte se lee una vez, salen los dos nibbles juntos, la activación se lee contigua
y se parte en pares/impares en registro con ``tl.split``, y el producto se cierra
con dos ``tl.dot`` sobre las mitades::

    packed = tl.load(w_ptrs)                    # una vez
    w_lo, w_hi = (packed & 15) - 8, ((packed >> 4) & 15) - 8
    a_even, a_odd = tl.split(tl.reshape(a, (BLOCK_M, BLOCK_K // 2, 2)))
    int_acc = tl.dot(a_even, w_lo) + tl.dot(a_odd, w_hi)

Además el acumulador pasó de bf16 (8 bits de mantisa, 96 parciales
encadenados) a INT32 por grupo con acumulación fp32, y el epílogo de escala
salió del bucle interno: antes se aplicaba una vez por cada ``BLOCK_K=32``.

Diseño (sm_86, mma.sync.aligned.m16n8k32.row.col.s32.s8.s8.s32):
  * ``BLOCK_K == GROUP_SIZE == 128`` -> una escala de grupo por iteración.
  * Tiles grandes, punteros que avanzan, grid 1-D con swizzle L2, num_stages 3-4.
  * Residual fusionado en el epílogo (strides 0 sobre un escalar cero cuando
    no hay residual: broadcast gratis, sin rama).

RowParallel: con TP>1 el residual se suma después del all_reduce; con TP=1 va
fusionado en el epílogo.


Los kernels son branchless y no validan nada: se asume todo comprobado.
"""

from __future__ import annotations

import torch
import triton
import triton.language as tl

try:
    from vllm._genesis.kernels.ptx_runtime import KernelNativo, habilitado
except ImportError:
    from ptx_runtime import KernelNativo, habilitado

_SK04 = "vllm._genesis.kernels.sk04_fa_o_w4a8"

_PTX_SRC_SK04_QUANT = r"""//
// Generated by LLVM NVPTX Back-End
//

.version 8.7
.target sm_86
.address_size 64

	// .globl	_sk04_fa_o_w4a8_quant_kernel // -- Begin function _sk04_fa_o_w4a8_quant_kernel
.extern .shared .align 16 .b8 global_smem[];
                                        // @_sk04_fa_o_w4a8_quant_kernel
.visible .entry _sk04_fa_o_w4a8_quant_kernel(
	.param .u64 .ptr .global .align 1 _sk04_fa_o_w4a8_quant_kernel_param_0,
	.param .u64 .ptr .global .align 1 _sk04_fa_o_w4a8_quant_kernel_param_1,
	.param .u64 .ptr .global .align 1 _sk04_fa_o_w4a8_quant_kernel_param_2,
	.param .u32 _sk04_fa_o_w4a8_quant_kernel_param_3,
	.param .u32 _sk04_fa_o_w4a8_quant_kernel_param_4,
	.param .u32 _sk04_fa_o_w4a8_quant_kernel_param_5,
	.param .u64 .ptr .global .align 1 _sk04_fa_o_w4a8_quant_kernel_param_6,
	.param .u64 .ptr .global .align 1 _sk04_fa_o_w4a8_quant_kernel_param_7
)
.reqntid 256
{
	.reg .pred 	%p<23>;
	.reg .b16 	%rs<17>;
	.reg .b32 	%r<207>;
	.reg .b64 	%rd<12>;
	.loc	1 113 0                         // sk04_fa_o_w4a8.py:113:0
$L__func_begin0:
	.loc	1 113 0                         // sk04_fa_o_w4a8.py:113:0

// %bb.0:
	ld.param.b64 	%rd5, [_sk04_fa_o_w4a8_quant_kernel_param_0];
	ld.param.b64 	%rd6, [_sk04_fa_o_w4a8_quant_kernel_param_1];
$L__tmp0:
	.loc	1 115 24                        // sk04_fa_o_w4a8.py:115:24
	mov.u32 	%r20, %ctaid.x;
	ld.param.b64 	%rd7, [_sk04_fa_o_w4a8_quant_kernel_param_2];
	.loc	1 116 24                        // sk04_fa_o_w4a8.py:116:24
	mov.u32 	%r21, %tid.x;
	and.b32 	%r22, %r21, 255;
	ld.param.b32 	%r23, [_sk04_fa_o_w4a8_quant_kernel_param_3];
	and.b32 	%r24, %r21, 31;
	ld.param.b32 	%r25, [_sk04_fa_o_w4a8_quant_kernel_param_4];
	shr.u32 	%r26, %r21, 5;
	ld.param.b32 	%r27, [_sk04_fa_o_w4a8_quant_kernel_param_5];
	shl.b32 	%r28, %r21, 4;
	and.b32 	%r29, %r28, 4080;
	.loc	1 117 18                        // sk04_fa_o_w4a8.py:117:18
	setp.lt.s32 	%p1, %r29, %r23;
	.loc	1 118 30                        // sk04_fa_o_w4a8.py:118:30
	mul.lo.s32 	%r30, %r25, %r20;
	.loc	1 118 24                        // sk04_fa_o_w4a8.py:118:24
	mad.wide.s32 	%rd8, %r30, 2, %rd5;
	.loc	1 118 42                        // sk04_fa_o_w4a8.py:118:42
	cvt.u64.u32 	%rd9, %r29;
	mad.wide.u32 	%rd1, %r29, 2, %rd8;
	add.s64 	%rd2, %rd1, 16;
	mov.b32 	%r5, 0;
	.loc	1 118 16                        // sk04_fa_o_w4a8.py:118:16
	// begin inline asm
	mov.u32 %r1, %r5;
	mov.u32 %r2, %r5;
	mov.u32 %r3, %r5;
	mov.u32 %r4, %r5;
	@%p1 ld.global.v4.b32 { %r1, %r2, %r3, %r4 }, [ %rd1 + 0 ];
	// end inline asm
	// begin inline asm
	mov.u32 %r6, %r5;
	mov.u32 %r7, %r5;
	mov.u32 %r8, %r5;
	mov.u32 %r9, %r5;
	@%p1 ld.global.v4.b32 { %r6, %r7, %r8, %r9 }, [ %rd2 + 0 ];
	// end inline asm
$L__tmp1:
	.loc	2 191 40                        // standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ]
	setp.eq.b32 	%p2, %r24, 0;
	shr.u32 	%r31, %r21, 3;
	and.b32 	%r32, %r31, 28;
	mov.b32 	%r33, global_smem;
	add.s32 	%r10, %r33, %r32;
	setp.lt.u32 	%p3, %r22, 8;
	shl.b32 	%r34, %r22, 2;
	add.s32 	%r13, %r33, %r34;
	and.b32 	%r35, %r21, 7;
	setp.eq.b32 	%p6, %r35, 0;
	and.pred 	%p4, %p3, %p6;
$L__tmp2:
	.loc	1 122 27                        // sk04_fa_o_w4a8.py:122:27
	mul.lo.s32 	%r36, %r27, %r20;
	.loc	1 122 21                        // sk04_fa_o_w4a8.py:122:21
	cvt.s64.s32 	%rd10, %r36;
	add.s64 	%rd11, %rd6, %rd10;
	.loc	1 122 39                        // sk04_fa_o_w4a8.py:122:39
	add.s64 	%rd3, %rd11, %rd9;
	.loc	1 118 73                        // sk04_fa_o_w4a8.py:118:73
	mov.b32 	{%rs1, %rs2}, %r9;
	cvt.f32.bf16 	%r37, %rs2;
	cvt.f32.bf16 	%r38, %rs1;
	mov.b32 	{%rs3, %rs4}, %r8;
	cvt.f32.bf16 	%r39, %rs4;
	cvt.f32.bf16 	%r40, %rs3;
	.loc	1 119 36                        // sk04_fa_o_w4a8.py:119:36
	abs.f32 	%r41, %r40;
	abs.f32 	%r42, %r39;
	abs.f32 	%r43, %r38;
	abs.f32 	%r44, %r37;
	.loc	1 118 73                        // sk04_fa_o_w4a8.py:118:73
	mov.b32 	{%rs5, %rs6}, %r7;
	cvt.f32.bf16 	%r45, %rs6;
	cvt.f32.bf16 	%r46, %rs5;
	mov.b32 	{%rs7, %rs8}, %r6;
	cvt.f32.bf16 	%r47, %rs8;
	cvt.f32.bf16 	%r48, %rs7;
	.loc	1 119 36                        // sk04_fa_o_w4a8.py:119:36
	abs.f32 	%r49, %r48;
	abs.f32 	%r50, %r47;
	abs.f32 	%r51, %r46;
	abs.f32 	%r52, %r45;
	.loc	1 118 73                        // sk04_fa_o_w4a8.py:118:73
	mov.b32 	{%rs9, %rs10}, %r4;
	cvt.f32.bf16 	%r53, %rs10;
	cvt.f32.bf16 	%r54, %rs9;
	mov.b32 	{%rs11, %rs12}, %r3;
	cvt.f32.bf16 	%r55, %rs12;
	cvt.f32.bf16 	%r56, %rs11;
	.loc	1 119 36                        // sk04_fa_o_w4a8.py:119:36
	abs.f32 	%r57, %r56;
	abs.f32 	%r58, %r55;
	abs.f32 	%r59, %r54;
	abs.f32 	%r60, %r53;
	.loc	1 118 73                        // sk04_fa_o_w4a8.py:118:73
	mov.b32 	{%rs13, %rs14}, %r2;
	cvt.f32.bf16 	%r61, %rs14;
	cvt.f32.bf16 	%r62, %rs13;
	mov.b32 	{%rs15, %rs16}, %r1;
	cvt.f32.bf16 	%r63, %rs16;
	cvt.f32.bf16 	%r64, %rs15;
	.loc	1 119 36                        // sk04_fa_o_w4a8.py:119:36
	abs.f32 	%r65, %r64;
	abs.f32 	%r66, %r63;
	abs.f32 	%r67, %r62;
	abs.f32 	%r68, %r61;
$L__tmp3:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ] ]
	max.f32 	%r69, %r65, %r66;
	max.f32 	%r70, %r69, %r67;
	max.f32 	%r71, %r70, %r68;
	max.f32 	%r72, %r71, %r57;
	max.f32 	%r73, %r72, %r58;
	max.f32 	%r74, %r73, %r59;
	max.f32 	%r75, %r74, %r60;
	max.f32 	%r76, %r75, %r49;
	max.f32 	%r77, %r76, %r50;
	max.f32 	%r78, %r77, %r51;
	max.f32 	%r79, %r78, %r52;
	max.f32 	%r80, %r79, %r41;
	max.f32 	%r81, %r80, %r42;
	max.f32 	%r82, %r81, %r43;
	max.f32 	%r83, %r82, %r44;
$L__tmp4:
	.loc	2 191 40                        // standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ]
	shfl.sync.bfly.b32 	%r84, %r83, 16, 31, -1;
$L__tmp5:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ] ]
	max.f32 	%r85, %r83, %r84;
$L__tmp6:
	.loc	2 191 40                        // standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ]
	shfl.sync.bfly.b32 	%r86, %r85, 8, 31, -1;
$L__tmp7:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ] ]
	max.f32 	%r87, %r85, %r86;
$L__tmp8:
	.loc	2 191 40                        // standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ]
	shfl.sync.bfly.b32 	%r88, %r87, 4, 31, -1;
$L__tmp9:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ] ]
	max.f32 	%r89, %r87, %r88;
$L__tmp10:
	.loc	2 191 40                        // standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ]
	shfl.sync.bfly.b32 	%r90, %r89, 2, 31, -1;
$L__tmp11:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ] ]
	max.f32 	%r91, %r89, %r90;
$L__tmp12:
	.loc	2 191 40                        // standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ]
	shfl.sync.bfly.b32 	%r92, %r91, 1, 31, -1;
$L__tmp13:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ] ]
	max.f32 	%r11, %r91, %r92;
$L__tmp14:
	.loc	2 191 40                        // standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ]
	// begin inline asm
	@%p2 st.shared.b32 [ %r10 + 0 ], %r11;
	// end inline asm
	bar.sync 	0;
	// begin inline asm
	@%p3 ld.shared.b32 %r12, [ %r13 + 0 ];
	// end inline asm
	shfl.sync.bfly.b32 	%r93, %r12, 4, 31, -1;
$L__tmp15:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ] ]
	max.f32 	%r94, %r12, %r93;
$L__tmp16:
	.loc	2 191 40                        // standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ]
	shfl.sync.bfly.b32 	%r95, %r94, 2, 31, -1;
$L__tmp17:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ] ]
	max.f32 	%r96, %r94, %r95;
$L__tmp18:
	.loc	2 191 40                        // standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ]
	shfl.sync.bfly.b32 	%r97, %r96, 1, 31, -1;
$L__tmp19:
	.loc	2 170 27                        // standard.py:170:27 @[ standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ] ]
	max.f32 	%r14, %r96, %r97;
$L__tmp20:
	.loc	2 191 40                        // standard.py:191:40 @[ sk04_fa_o_w4a8.py:119:29 ]
	// begin inline asm
	@%p4 st.shared.b32 [ %r13 + 0 ], %r14;
	// end inline asm
	bar.sync 	0;
	ld.shared.b32 	%r98, [global_smem];
$L__tmp21:
	.loc	1 119 49                        // sk04_fa_o_w4a8.py:119:49
	max.f32 	%r99, %r98, 0f0DA24260;
	mov.b32 	%r100, 0f42FE0000;
	.loc	1 120 22                        // sk04_fa_o_w4a8.py:120:22
	div.full.f32 	%r101, %r100, %r99;
	.loc	1 120 14                        // sk04_fa_o_w4a8.py:120:14
	mul.f32 	%r102, %r101, %r63;
	mul.f32 	%r103, %r101, %r64;
	mul.f32 	%r104, %r101, %r61;
	mul.f32 	%r105, %r101, %r62;
	mul.f32 	%r106, %r101, %r55;
	mul.f32 	%r107, %r101, %r56;
	mul.f32 	%r108, %r101, %r53;
	mul.f32 	%r109, %r101, %r54;
	mul.f32 	%r110, %r101, %r47;
	mul.f32 	%r111, %r101, %r48;
	mul.f32 	%r112, %r101, %r45;
	mul.f32 	%r113, %r101, %r46;
	mul.f32 	%r114, %r101, %r39;
	mul.f32 	%r115, %r101, %r40;
	mul.f32 	%r116, %r101, %r37;
	mul.f32 	%r117, %r101, %r38;
	.loc	1 121 29                        // sk04_fa_o_w4a8.py:121:29
	.loc	1 121 39                        // sk04_fa_o_w4a8.py:121:39
	lop3.b32 	%r118, 0x3f000000, %r102, 0x80000000, 0xF8;
	lop3.b32 	%r119, 0x3f000000, %r103, 0x80000000, 0xF8;
	lop3.b32 	%r120, 0x3f000000, %r104, 0x80000000, 0xF8;
	lop3.b32 	%r121, 0x3f000000, %r105, 0x80000000, 0xF8;
	lop3.b32 	%r122, 0x3f000000, %r106, 0x80000000, 0xF8;
	lop3.b32 	%r123, 0x3f000000, %r107, 0x80000000, 0xF8;
	lop3.b32 	%r124, 0x3f000000, %r108, 0x80000000, 0xF8;
	lop3.b32 	%r125, 0x3f000000, %r109, 0x80000000, 0xF8;
	lop3.b32 	%r126, 0x3f000000, %r110, 0x80000000, 0xF8;
	lop3.b32 	%r127, 0x3f000000, %r111, 0x80000000, 0xF8;
	lop3.b32 	%r128, 0x3f000000, %r112, 0x80000000, 0xF8;
	lop3.b32 	%r129, 0x3f000000, %r113, 0x80000000, 0xF8;
	lop3.b32 	%r130, 0x3f000000, %r114, 0x80000000, 0xF8;
	lop3.b32 	%r131, 0x3f000000, %r115, 0x80000000, 0xF8;
	lop3.b32 	%r132, 0x3f000000, %r116, 0x80000000, 0xF8;
	lop3.b32 	%r133, 0x3f000000, %r117, 0x80000000, 0xF8;
	.loc	1 121 14                        // sk04_fa_o_w4a8.py:121:14
	fma.rn.f32 	%r134, %r101, %r62, %r121;
	fma.rn.f32 	%r135, %r101, %r61, %r120;
	fma.rn.f32 	%r136, %r101, %r64, %r119;
	fma.rn.f32 	%r137, %r101, %r63, %r118;
	fma.rn.f32 	%r138, %r101, %r54, %r125;
	fma.rn.f32 	%r139, %r101, %r53, %r124;
	fma.rn.f32 	%r140, %r101, %r56, %r123;
	fma.rn.f32 	%r141, %r101, %r55, %r122;
	fma.rn.f32 	%r142, %r101, %r46, %r129;
	fma.rn.f32 	%r143, %r101, %r45, %r128;
	fma.rn.f32 	%r144, %r101, %r48, %r127;
	fma.rn.f32 	%r145, %r101, %r47, %r126;
	fma.rn.f32 	%r146, %r101, %r38, %r133;
	fma.rn.f32 	%r147, %r101, %r37, %r132;
	fma.rn.f32 	%r148, %r101, %r40, %r131;
	fma.rn.f32 	%r149, %r101, %r39, %r130;
	.loc	1 121 49                        // sk04_fa_o_w4a8.py:121:49
	cvt.rzi.s32.f32 	%r150, %r137;
	cvt.rzi.s32.f32 	%r151, %r136;
	cvt.rzi.s32.f32 	%r152, %r135;
	cvt.rzi.s32.f32 	%r153, %r134;
	cvt.rzi.s32.f32 	%r154, %r141;
	cvt.rzi.s32.f32 	%r155, %r140;
	cvt.rzi.s32.f32 	%r156, %r139;
	cvt.rzi.s32.f32 	%r157, %r138;
	cvt.rzi.s32.f32 	%r158, %r145;
	cvt.rzi.s32.f32 	%r159, %r144;
	cvt.rzi.s32.f32 	%r160, %r143;
	cvt.rzi.s32.f32 	%r161, %r142;
	cvt.rzi.s32.f32 	%r162, %r149;
	cvt.rzi.s32.f32 	%r163, %r148;
	cvt.rzi.s32.f32 	%r164, %r147;
	cvt.rzi.s32.f32 	%r165, %r146;
	.loc	1 122 70                        // sk04_fa_o_w4a8.py:122:70
	max.s32 	%r166, %r153, -127;
	max.s32 	%r167, %r152, -127;
	max.s32 	%r168, %r151, -127;
	max.s32 	%r169, %r150, -127;
	max.s32 	%r170, %r157, -127;
	max.s32 	%r171, %r156, -127;
	max.s32 	%r172, %r155, -127;
	max.s32 	%r173, %r154, -127;
	max.s32 	%r174, %r161, -127;
	max.s32 	%r175, %r160, -127;
	max.s32 	%r176, %r159, -127;
	max.s32 	%r177, %r158, -127;
	max.s32 	%r178, %r165, -127;
	max.s32 	%r179, %r164, -127;
	max.s32 	%r180, %r163, -127;
	max.s32 	%r181, %r162, -127;
	.loc	1 122 77                        // sk04_fa_o_w4a8.py:122:77
	min.s32 	%r182, %r169, 127;
	min.s32 	%r183, %r168, 127;
	min.s32 	%r184, %r167, 127;
	min.s32 	%r185, %r166, 127;
	min.s32 	%r186, %r173, 127;
	min.s32 	%r187, %r172, 127;
	min.s32 	%r188, %r171, 127;
	min.s32 	%r189, %r170, 127;
	min.s32 	%r190, %r177, 127;
	min.s32 	%r191, %r176, 127;
	min.s32 	%r192, %r175, 127;
	min.s32 	%r193, %r174, 127;
	min.s32 	%r194, %r181, 127;
	min.s32 	%r195, %r180, 127;
	min.s32 	%r196, %r179, 127;
	min.s32 	%r197, %r178, 127;
	.loc	1 122 85                        // sk04_fa_o_w4a8.py:122:85
	prmt.b32 	%r198, %r185, %r184, 0x3340U;
	prmt.b32 	%r199, %r183, %r182, 0x3340U;
	prmt.b32 	%r15, %r199, %r198, 0x5410U;
	prmt.b32 	%r200, %r189, %r188, 0x3340U;
	prmt.b32 	%r201, %r187, %r186, 0x3340U;
	prmt.b32 	%r16, %r201, %r200, 0x5410U;
	prmt.b32 	%r202, %r193, %r192, 0x3340U;
	prmt.b32 	%r203, %r191, %r190, 0x3340U;
	prmt.b32 	%r17, %r203, %r202, 0x5410U;
	prmt.b32 	%r204, %r197, %r196, 0x3340U;
	prmt.b32 	%r205, %r195, %r194, 0x3340U;
	prmt.b32 	%r18, %r205, %r204, 0x5410U;
	.loc	1 122 45                        // sk04_fa_o_w4a8.py:122:45
	// begin inline asm
	@%p1 st.global.v4.b32 [ %rd3 + 0 ], { %r15, %r16, %r17, %r18 };
	// end inline asm
	.loc	1 123 21                        // sk04_fa_o_w4a8.py:123:21
	mad.wide.u32 	%rd4, %r20, 4, %rd7;
	.loc	1 123 34                        // sk04_fa_o_w4a8.py:123:34
	mul.f32 	%r19, %r99, 0f3C010204;
	.loc	1 123 26                        // sk04_fa_o_w4a8.py:123:26
	or.b32 	%r206, %r24, %r26;
	setp.eq.b32 	%p5, %r206, 0;
	// begin inline asm
	@%p5 st.global.b32 [ %rd4 + 0 ], { %r19 };
	// end inline asm
	.loc	1 123 4                         // sk04_fa_o_w4a8.py:123:4
	ret;
$L__tmp22:
$L__func_end0:
                                        // -- End function
}
	.file	1 "/home/usuario/Proyectos/genesis-vllm-patches/vllm/_genesis/kernels/sk04_fa_o_w4a8.py"
	.file	2 "/home/usuario/Proyectos/genesis-vllm-patches/.venv/lib/python3.12/site-packages/triton/language/standard.py"
	.section	.debug_abbrev
	{
.b8 1                                   // Abbreviation Code
.b8 17                                  // DW_TAG_compile_unit
.b8 1                                   // DW_CHILDREN_yes
.b8 37                                  // DW_AT_producer
.b8 8                                   // DW_FORM_string
.b8 19                                  // DW_AT_language
.b8 5                                   // DW_FORM_data2
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 16                                  // DW_AT_stmt_list
.b8 6                                   // DW_FORM_data4
.b8 27                                  // DW_AT_comp_dir
.b8 8                                   // DW_FORM_string
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 2                                   // Abbreviation Code
.b8 46                                  // DW_TAG_subprogram
.b8 0                                   // DW_CHILDREN_no
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 32                                  // DW_AT_inline
.b8 11                                  // DW_FORM_data1
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 3                                   // Abbreviation Code
.b8 46                                  // DW_TAG_subprogram
.b8 1                                   // DW_CHILDREN_yes
.b8 17                                  // DW_AT_low_pc
.b8 1                                   // DW_FORM_addr
.b8 18                                  // DW_AT_high_pc
.b8 1                                   // DW_FORM_addr
.b8 49                                  // DW_AT_abstract_origin
.b8 19                                  // DW_FORM_ref4
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 4                                   // Abbreviation Code
.b8 29                                  // DW_TAG_inlined_subroutine
.b8 1                                   // DW_CHILDREN_yes
.b8 49                                  // DW_AT_abstract_origin
.b8 19                                  // DW_FORM_ref4
.b8 17                                  // DW_AT_low_pc
.b8 1                                   // DW_FORM_addr
.b8 18                                  // DW_AT_high_pc
.b8 1                                   // DW_FORM_addr
.b8 88                                  // DW_AT_call_file
.b8 11                                  // DW_FORM_data1
.b8 89                                  // DW_AT_call_line
.b8 11                                  // DW_FORM_data1
.b8 87                                  // DW_AT_call_column
.b8 11                                  // DW_FORM_data1
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 5                                   // Abbreviation Code
.b8 29                                  // DW_TAG_inlined_subroutine
.b8 0                                   // DW_CHILDREN_no
.b8 49                                  // DW_AT_abstract_origin
.b8 19                                  // DW_FORM_ref4
.b8 17                                  // DW_AT_low_pc
.b8 1                                   // DW_FORM_addr
.b8 18                                  // DW_AT_high_pc
.b8 1                                   // DW_FORM_addr
.b8 88                                  // DW_AT_call_file
.b8 11                                  // DW_FORM_data1
.b8 89                                  // DW_AT_call_line
.b8 11                                  // DW_FORM_data1
.b8 87                                  // DW_AT_call_column
.b8 11                                  // DW_FORM_data1
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 0                                   // EOM(3)
	}
	.section	.debug_info
	{
.b32 209                                // Length of Unit
.b8 2                                   // DWARF version number
.b8 0
.b32 .debug_abbrev                      // Offset Into Abbrev. Section
.b8 8                                   // Address Size (in bytes)
.b8 1                                   // Abbrev [1] 0xb:0xca DW_TAG_compile_unit
.b8 116                                 // DW_AT_producer
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2                                   // DW_AT_language
.b8 0
.b8 115                                 // DW_AT_name
.b8 107
.b8 48
.b8 52
.b8 95
.b8 102
.b8 97
.b8 95
.b8 111
.b8 95
.b8 119
.b8 52
.b8 97
.b8 56
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line                        // DW_AT_stmt_list
.b8 47                                  // DW_AT_comp_dir
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 117
.b8 115
.b8 117
.b8 97
.b8 114
.b8 105
.b8 111
.b8 47
.b8 80
.b8 114
.b8 111
.b8 121
.b8 101
.b8 99
.b8 116
.b8 111
.b8 115
.b8 47
.b8 103
.b8 101
.b8 110
.b8 101
.b8 115
.b8 105
.b8 115
.b8 45
.b8 118
.b8 108
.b8 108
.b8 109
.b8 45
.b8 112
.b8 97
.b8 116
.b8 99
.b8 104
.b8 101
.b8 115
.b8 47
.b8 118
.b8 108
.b8 108
.b8 109
.b8 47
.b8 95
.b8 103
.b8 101
.b8 110
.b8 101
.b8 115
.b8 105
.b8 115
.b8 47
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 115
.b8 0
.b8 2                                   // Abbrev [2] 0x6e:0x1f DW_TAG_subprogram
.b8 95                                  // DW_AT_name
.b8 115
.b8 107
.b8 48
.b8 52
.b8 95
.b8 102
.b8 97
.b8 95
.b8 111
.b8 95
.b8 119
.b8 52
.b8 97
.b8 56
.b8 95
.b8 113
.b8 117
.b8 97
.b8 110
.b8 116
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 0
.b8 1                                   // DW_AT_inline
.b8 3                                   // Abbrev [3] 0x8d:0x47 DW_TAG_subprogram
.b64 $L__func_begin0                    // DW_AT_low_pc
.b64 $L__func_end0                      // DW_AT_high_pc
.b32 110                                // DW_AT_abstract_origin
.b8 4                                   // Abbrev [4] 0xa2:0x31 DW_TAG_inlined_subroutine
.b32 110                                // DW_AT_abstract_origin
.b64 $L__tmp1                           // DW_AT_low_pc
.b64 $L__tmp21                          // DW_AT_high_pc
.b8 1                                   // DW_AT_call_file
.b8 119                                 // DW_AT_call_line
.b8 29                                  // DW_AT_call_column
.b8 5                                   // Abbrev [5] 0xba:0x18 DW_TAG_inlined_subroutine
.b32 110                                // DW_AT_abstract_origin
.b64 $L__tmp3                           // DW_AT_low_pc
.b64 $L__tmp20                          // DW_AT_high_pc
.b8 2                                   // DW_AT_call_file
.b8 191                                 // DW_AT_call_line
.b8 40                                  // DW_AT_call_column
.b8 0                                   // End Of Children Mark
.b8 0                                   // End Of Children Mark
.b8 0                                   // End Of Children Mark
	}
	.section	.debug_macinfo	{	}
"""

_PTX_KERNEL_SK04_QUANT = KernelNativo(
    "B2/sk04_fa_o_w4a8.py__quant", _PTX_SRC_SK04_QUANT,
    num_warps=8, shared=32, idx=[0, 1, 2, 3, 4, 5], n_runtime=6,
    horneado={6: 4096},
)

SK_ID = "SK-04-W4A8"
SK_NAME = "FA_O_W4A8"
GLOBAL_SHAPE = (5120, 6144)
RANK_SHAPE = (5120, 3072)
NUM_LAYERS = 17
ROW_PARALLEL = True

GROUP_SIZE: int = 128

# Split-K de decode: reparte K entre CTAs cuando hay pocos bloques de N.
SPLITK_MAX_M: int = 32
SPLITK_BLOCK_N: int = 128
SPLITK_BLOCK_K: int = 128
SPLIT_K: int = 4
# GA102 (RTX 3090) tiene 82 SM. El split-K sólo paga cuando N/BLOCK_N no llega
# a llenar una ola: con N=17408 ya hay 136 CTAs y repartir K sólo agrega
# atómicas y un buffer fp32 intermedio (medido: 0.081 -> 0.100 ms a M=1).
SM_COUNT: int = 82

# (BLOCK_M, BLOCK_N, BLOCK_K, GROUP_M, num_warps, num_stages) por bucket de M.
# BLOCK_K == GROUP_SIZE == 128 -> una escala de grupo por iteración.
_CFG: tuple[tuple[int, int, int, int, int, int], ...] = (
    # (BLOCK_M, BLOCK_N, BLOCK_K, GROUP_M, num_warps, num_stages) por bucket de M.
    # Barrido propio de W4A8 en RTX 3090 (K=5120, N=8192), mediana de 5 corridas.
    # Su perfil NO es el de W8A8: aca el kernel esta ALU-bound desempaquetando
    # nibbles, asi que gana con menos warps (4) y mas stages, no con tiles mas
    # grandes. Ganancia sobre la config anterior:
    #   M=32 1.18x   M=128 1.24x   M=512 1.26x   M=1664 1.20x   M=8000 1.23x
    (16, 128, 128, 8, 8, 3),    # M <=   16  decode
    (64, 128, 128, 8, 4, 4),    # M <=  128
    (64, 128, 128, 8, 4, 4),    # M <= 1024
    (128, 256, 64, 8, 8, 3),    # M  > 1024  prefill
)

BLOCK_M: int = 64
BLOCK_N: int = 128
BLOCK_K: int = 128

_ZERO: dict[torch.device, torch.Tensor] = {}


def _zero(device: torch.device) -> torch.Tensor:
    """Escalar cero por device, usado como residual neutro con strides 0."""
    z = _ZERO.get(device)
    if z is None:
        z = torch.zeros((), dtype=torch.bfloat16, device=device)
        _ZERO[device] = z
    return z


def _cfg(m: int) -> tuple[int, int, int, int, int, int]:
    return _CFG[(m > 16) + (m > 128) + (m > 1024)]


@triton.jit
def _sk04_fa_o_w4a8_quant_kernel(x_ptr, q_ptr, s_ptr, K, stride_xm, stride_qm, BLOCK: tl.constexpr):
    """Quant per-token amax/127, una fila por programa."""
    row = tl.program_id(0)
    offs = tl.arange(0, BLOCK)
    mask = offs < K
    x = tl.load(x_ptr + row * stride_xm + offs, mask=mask, other=0.0).to(tl.float32)
    amax = tl.maximum(tl.max(tl.abs(x), axis=0), 1e-30)
    xq = x * (127.0 / amax)
    q = (xq + tl.where(xq >= 0.0, 0.5, -0.5)).to(tl.int32)
    tl.store(q_ptr + row * stride_qm + offs, tl.minimum(tl.maximum(q, -127), 127).to(tl.int8), mask=mask)
    tl.store(s_ptr + row, amax * (1.0 / 127.0))


@triton.jit
def _sk04_fa_o_w4a8_splitk_kernel(
    a_ptr, w_ptr, out_ptr, a_scale_ptr, w_scale_ptr,
    M, N, K,
    stride_am, stride_ak, stride_wk, stride_wn,
    stride_out_m, stride_out_n,
    stride_ws_g, stride_ws_n,
    BLOCK_M: tl.constexpr, BLOCK_N: tl.constexpr, BLOCK_K: tl.constexpr,
    SPLIT_K: tl.constexpr,
):
    """Variante split-K para decode: reparte K entre ``SPLIT_K`` CTAs.

    El grid es (M/BLOCK_M, N/BLOCK_N, SPLIT_K). La dimension de M es
    obligatoria: sin ella el kernel calculaba SOLO las primeras BLOCK_M=16
    filas y las de arriba quedaban sin escribir. Medido antes del fix: a M=17
    salian mal 3 de 17 filas, a M=32 salian mal 19 de 32.

    En decode el GEMM es bandwidth-bound sobre el peso, pero con ``BLOCK_N=128``
    una capa como ``down_proj`` (N=5120) sólo genera 40 CTAs para 82 SM: media
    GPU parada. Repartiendo K en 4 se llega a 160 y el ancho de banda sube de
    32% a 57% del techo de la 3090. Cada trozo aplica sus propias escalas de
    grupo y de fila, así que la reducción entre trozos es una suma directa
    (``tl.atomic_add`` sobre fp32).
    """
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)
    pid_k = tl.program_id(2)
    offs_m = (pid_m * BLOCK_M + tl.arange(0, BLOCK_M)) % M
    offs_n = (pid_n * BLOCK_N + tl.arange(0, BLOCK_N)) % N
    offs_k = tl.arange(0, BLOCK_K)
    offs_kh = tl.arange(0, BLOCK_K // 2)

    groups = (K // BLOCK_K) // SPLIT_K
    g0 = pid_k * groups
    a_ptrs = a_ptr + offs_m[:, None] * stride_am + (g0 * BLOCK_K + offs_k)[None, :] * stride_ak
    w_ptrs = w_ptr + (g0 * (BLOCK_K // 2) + offs_kh)[:, None] * stride_wk + offs_n[None, :] * stride_wn

    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float32)
    for g in range(groups):
        packed = tl.load(w_ptrs).to(tl.int32)
        w_lo = ((packed & 15) - 8).to(tl.int8)
        w_hi = (((packed >> 4) & 15) - 8).to(tl.int8)
        a_even, a_odd = tl.split(tl.reshape(tl.load(a_ptrs), (BLOCK_M, BLOCK_K // 2, 2)))
        int_acc = tl.dot(a_even, w_lo, out_dtype=tl.int32) + tl.dot(a_odd, w_hi, out_dtype=tl.int32)
        w_scales = tl.load(w_scale_ptr + (g0 + g) * stride_ws_g + offs_n * stride_ws_n).to(tl.float32)
        acc += int_acc.to(tl.float32) * w_scales[None, :]
        a_ptrs += BLOCK_K * stride_ak
        w_ptrs += (BLOCK_K // 2) * stride_wk

    acc = acc * tl.load(a_scale_ptr + offs_m).to(tl.float32)[:, None]
    out_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    out_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    tl.atomic_add(
        out_ptr + out_m[:, None] * stride_out_m + out_n[None, :] * stride_out_n,
        acc,
        mask=(out_m[:, None] < M) & (out_n[None, :] < N),
    )


@triton.jit
def _sk04_fa_o_w4a8_kernel(
    a_ptr, w_ptr, out_ptr, resid_ptr, a_scale_ptr, w_scale_ptr,
    M, N, K,
    stride_am, stride_ak, stride_wk, stride_wn,
    stride_out_m, stride_out_n, stride_res_m, stride_res_n,
    stride_ws_g, stride_ws_n,
    BLOCK_M: tl.constexpr, BLOCK_N: tl.constexpr, BLOCK_K: tl.constexpr,
    GROUP_M: tl.constexpr,
):
    """GEMM W4A8: activación INT8 per-token, peso INT4 empacado con escala por grupo."""
    pid = tl.program_id(0)
    num_pid_m = tl.cdiv(M, BLOCK_M)
    num_pid_n = tl.cdiv(N, BLOCK_N)
    pid_in_group = GROUP_M * num_pid_n
    first_m = (pid // pid_in_group) * GROUP_M
    group_m = min(num_pid_m - first_m, GROUP_M)
    pid_m = first_m + ((pid % pid_in_group) % group_m)
    pid_n = (pid % pid_in_group) // group_m

    offs_m = (pid_m * BLOCK_M + tl.arange(0, BLOCK_M)) % M
    offs_n = (pid_n * BLOCK_N + tl.arange(0, BLOCK_N)) % N
    offs_k = tl.arange(0, BLOCK_K)
    offs_kh = tl.arange(0, BLOCK_K // 2)

    a_ptrs = a_ptr + offs_m[:, None] * stride_am + offs_k[None, :] * stride_ak
    w_ptrs = w_ptr + offs_kh[:, None] * stride_wk + offs_n[None, :] * stride_wn

    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float32)
    for g in range(0, K // BLOCK_K):
        # Una sola lectura del byte empacado: los dos nibbles salen a la vez.
        packed = tl.load(w_ptrs).to(tl.int32)
        w_lo = ((packed & 15) - 8).to(tl.int8)
        w_hi = (((packed >> 4) & 15) - 8).to(tl.int8)
        # La activación se lee contigua y se parte en pares/impares en registro.
        a_even, a_odd = tl.split(tl.reshape(tl.load(a_ptrs), (BLOCK_M, BLOCK_K // 2, 2)))
        int_acc = tl.dot(a_even, w_lo, out_dtype=tl.int32) + tl.dot(a_odd, w_hi, out_dtype=tl.int32)
        w_scales = tl.load(w_scale_ptr + g * stride_ws_g + offs_n * stride_ws_n).to(tl.float32)
        acc += int_acc.to(tl.float32) * w_scales[None, :]
        a_ptrs += BLOCK_K * stride_ak
        w_ptrs += (BLOCK_K // 2) * stride_wk

    acc = acc * tl.load(a_scale_ptr + offs_m).to(tl.float32)[:, None]
    acc += tl.load(resid_ptr + offs_m[:, None] * stride_res_m + offs_n[None, :] * stride_res_n).to(tl.float32)

    out_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    out_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    tl.store(
        out_ptr + out_m[:, None] * stride_out_m + out_n[None, :] * stride_out_n,
        acc.to(out_ptr.dtype.element_ty),
        mask=(out_m[:, None] < M) & (out_n[None, :] < N),
    )


def sk04_fa_o_w4a8_quant_triton(hidden: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    """Quant per-token INT8 -> ``(q [M,K] int8, s [M] fp32)``. Camino Triton,
    referencia para tests (bit-exacto contra el PTX embebido)."""
    M, K = hidden.shape
    q = torch.empty((M, K), dtype=torch.int8, device=hidden.device)
    s = torch.empty((M,), dtype=torch.float32, device=hidden.device)
    _sk04_fa_o_w4a8_quant_kernel[(M,)](
        hidden, q, s, K, hidden.stride(0), q.stride(0),
        BLOCK=triton.next_power_of_2(K), num_warps=8, num_stages=1,
    )
    return q, s


def sk04_fa_o_w4a8_quant(hidden: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    """Quant per-token INT8 -> ``(q [M,K] int8, s [M] fp32)``. Camino de
    producción: PTX nativo embebido (libcuda cruda, sin JIT de Triton)."""
    M, K = hidden.shape
    q = torch.empty((M, K), dtype=torch.int8, device=hidden.device)
    s = torch.empty((M,), dtype=torch.float32, device=hidden.device)
    if habilitado():
        _PTX_KERNEL_SK04_QUANT(
            (M,), hidden, q, s, K, hidden.stride(0), q.stride(0),
            triton.next_power_of_2(K),
        )
        return q, s
    return sk04_fa_o_w4a8_quant_triton(hidden)


def sk04_fa_o_w4a8_gemm(
    a: torch.Tensor,
    w_packed: torch.Tensor,
    a_scales: torch.Tensor,
    w_scales: torch.Tensor,
    residual: torch.Tensor | None = None,
    out_dtype: torch.dtype = torch.bfloat16,
) -> torch.Tensor:
    """GEMM W4A8. ``a`` int8 [M,K], ``w_packed`` int8 [K/2,N], ``w_scales`` [K/128,N]."""
    M, K = a.shape
    N = w_packed.shape[1]
    res = _zero(a.device) if residual is None else residual
    rm, rn = (0, 0) if residual is None else (res.stride(0), res.stride(1))
    # Decode: split-K para no dejar SMs ociosos cuando N/BLOCK_N < 2 olas.
    if (
        M <= SPLITK_MAX_M
        and triton.cdiv(N, SPLITK_BLOCK_N) < SM_COUNT
        and (K // SPLITK_BLOCK_K) % SPLIT_K == 0
    ):
        acc = (
            torch.zeros((M, N), dtype=torch.float32, device=a.device)
            if residual is None
            else residual.to(torch.float32).expand(M, N).contiguous()
        )
        _sk04_fa_o_w4a8_splitk_kernel[(triton.cdiv(M, 16), triton.cdiv(N, SPLITK_BLOCK_N), SPLIT_K)](
            a, w_packed, acc, a_scales, w_scales,
            M, N, K,
            a.stride(0), a.stride(1), w_packed.stride(0), w_packed.stride(1),
            acc.stride(0), acc.stride(1),
            w_scales.stride(0), w_scales.stride(1),
            BLOCK_M=16, BLOCK_N=SPLITK_BLOCK_N, BLOCK_K=SPLITK_BLOCK_K, SPLIT_K=SPLIT_K,
            num_warps=4, num_stages=3,
        )
        return acc.to(out_dtype)
    bm, bn, bk, gm, warps, stages = _cfg(M)
    out = torch.empty((M, N), dtype=out_dtype, device=a.device)
    grid = (triton.cdiv(M, bm) * triton.cdiv(N, bn),)
    _sk04_fa_o_w4a8_kernel[grid](
        a, w_packed, out, res, a_scales, w_scales,
        M, N, K,
        a.stride(0), a.stride(1), w_packed.stride(0), w_packed.stride(1),
        out.stride(0), out.stride(1), rm, rn,
        w_scales.stride(0), w_scales.stride(1),
        BLOCK_M=bm, BLOCK_N=bn, BLOCK_K=bk, GROUP_M=gm,
        num_warps=warps, num_stages=stages,
    )
    return out


def sk04_fa_o_w4a8_proj(
    attn_out: torch.Tensor,
    w_packed: torch.Tensor,
    w_scales: torch.Tensor,
    residual: torch.Tensor | None = None,
    out_dtype: torch.dtype = torch.bfloat16,
    do_allreduce: bool = True,
) -> torch.Tensor:
    """Capa completa FA o_proj W4A8: quant -> GEMM -> all_reduce -> residual."""
    a, a_scales = sk04_fa_o_w4a8_quant(attn_out)
    if not do_allreduce:
        return sk04_fa_o_w4a8_gemm(a, w_packed, a_scales, w_scales, residual, out_dtype)
    out = sk04_fa_o_w4a8_gemm(a, w_packed, a_scales, w_scales, None, out_dtype)
    torch.distributed.all_reduce(out)
    out.add_(residual)
    return out


__all__ = [
    "SK_ID", "SK_NAME", "GLOBAL_SHAPE", "RANK_SHAPE", "NUM_LAYERS", "ROW_PARALLEL",
    "GROUP_SIZE", "BLOCK_M", "BLOCK_N", "BLOCK_K", "SPLIT_K", "SPLITK_MAX_M", "SM_COUNT",
    "sk04_fa_o_w4a8_quant", "sk04_fa_o_w4a8_gemm", "sk04_fa_o_w4a8_proj",
]
